# Install Library

In [ ]:
# %pip install datasets

In [ ]:
# %pip install transformers

In [ ]:
# %pip install tensorflow

In [ ]:
# %pip install tf-keras

In [ ]:
# %pip install matplotlib

In [ ]:
# %pip install ipywidgets

In [ ]:
# %pip install sentencepiece

In [ ]:
# %pip install scikit-learn

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

# Load Datasets

## Load Data dari Hugging Face

In [ ]:
from datasets import load_dataset
import pandas as pd

In [ ]:
from huggingface_hub import login
login()

## Datasets Tunggal

### Wiki-Label Datasets

In [ ]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
wiki_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "wiki_labeled")

wiki_dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/210000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/45000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/45000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 210000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
})

In [ ]:
# Konversi dataset ke DataFrame Pandas
train_wiki_df = wiki_dataset["train"].to_pandas().iloc[:144000]
test_wiki_df = wiki_dataset["test"].to_pandas().iloc[:16000]
val_wiki_df = wiki_dataset["validation"].to_pandas().iloc[:16000]

In [ ]:
print(f"Ukuran Train Wiki-Label: {train_wiki_df.shape}")
print(f"Ukuran Test Wiki-Label: {test_wiki_df.shape}")
print(f"Ukuran Val Wiki-Label: {val_wiki_df.shape}")

Ukuran Train Wiki-Label: (144000, 4)
Ukuran Test Wiki-Label: (16000, 4)
Ukuran Val Wiki-Label: (16000, 4)


In [ ]:
train_wiki_df

title  label  \
0                   James Scobie      0   
1                   James Scobie      1   
2                   Dagliç sheep      0   
3                   Dagliç sheep      1   
4                  Hamdard India      0   
...                          ...    ...   
143995             Diggers' Song      1   
143996  Geylang International FC      0   
143997  Geylang International FC      1   
143998        Takayama Main Line      0   
143999        Takayama Main Line      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
143995  The "Diggers' Song" (also known as "Levellers'...         218  
143996  Geylang International Football Club is a profe...         166  
143997  Geylang International Football Club is a profe...         207  
143998  The  is a Japanese railway line between Gifu S...         180  
143999  The  is a Japanese railway line connecting the...          72  

[144000 rows x 4 columns]

### Research-Abstract-Label Datasets

In [ ]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
abstract_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "research_abstracts_labeled")

abstract_dataset

Generating train split:   0%|          | 0/14000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 14000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
})

In [ ]:
# Konversi dataset ke DataFrame Pandas
train_abstract_df = abstract_dataset["train"].to_pandas()
test_abstract_df = abstract_dataset["test"].to_pandas()
val_abstract_df = abstract_dataset["validation"].to_pandas()

In [ ]:
print(f"Ukuran Train abstract-Label: {train_abstract_df.shape}")
print(f"Ukuran Test abstract-Label: {test_abstract_df.shape}")
print(f"Ukuran Val abstract-Label: {val_abstract_df.shape}")

Ukuran Train abstract-Label: (14000, 4)
Ukuran Test abstract-Label: (3000, 4)
Ukuran Val abstract-Label: (3000, 4)


In [ ]:
train_abstract_df

title  label  \
0      Study of coupling loss on bi-columnar BSCCO/Ag...      0   
1      Study of coupling loss on bi-columnar BSCCO/Ag...      1   
2      Weighted Solyanik estimates for the strong max...      0   
3      Weighted Solyanik estimates for the strong max...      1   
4      SOFIA-EXES Observations of Betelgeuse during t...      0   
...                                                  ...    ...   
13995  Effects of bonding type and interface geometry...      1   
13996  GOODS-Herschel: The far-infrared view of star ...      0   
13997  GOODS-Herschel: The far-infrared view of star ...      1   
13998  Single-qubit peration sharing with Bell and W ...      0   
13999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      Coupling losses were studied in composite tape...         280  
1      In this study, we investigate the coupling los...         215  
2      Let $\mathsf M_{\mathsf S}$ denote the strong ...         332  
3      In this paper, we investigate Weighted Solyani...         225  
4      In 2019 October Betelgeuse began a decline in ...         268  
...                                                  ...         ...  
13995  The coherent transport of magnetic information...         286  
13996  We present a study of the infrared properties ...         330  
13997  This paper presents the results of a study of ...         339  
13998  Two tripartite schemes are put forward with sh...          98  
13999  In quantum computing, sharing single-qubit ope...          95  

[14000 rows x 4 columns]

## Datasets Gabungan

### Datasets Gabungan Balance

In [ ]:
train_balMerg_df = pd.concat([train_wiki_df.iloc[:14000], train_abstract_df]).reset_index(drop=True)
val_balMerg_df = pd.concat([val_wiki_df.iloc[:3000], val_abstract_df]).reset_index(drop=True)
test_balMerg_df = pd.concat([test_wiki_df.iloc[:3000], test_abstract_df]).reset_index(drop=True)

In [ ]:
print(f"Ukuran Train abstract-Label: {train_balMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_balMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_balMerg_df.shape}")

Ukuran Train abstract-Label: (28000, 4)
Ukuran Test abstract-Label: (6000, 4)
Ukuran Val abstract-Label: (6000, 4)


In [ ]:
train_balMerg_df

title  label  \
0                                           James Scobie      0   
1                                           James Scobie      1   
2                                           Dagliç sheep      0   
3                                           Dagliç sheep      1   
4                                          Hamdard India      0   
...                                                  ...    ...   
27995  Effects of bonding type and interface geometry...      1   
27996  GOODS-Herschel: The far-infrared view of star ...      0   
27997  GOODS-Herschel: The far-infrared view of star ...      1   
27998  Single-qubit peration sharing with Bell and W ...      0   
27999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      James Scobie (29 November 1826 – 7 October 185...         175  
1      James Scobie (29 November 1826 – 7 October 189...         242  
2      The Dagliç is a breed of sheep found primarily...         152  
3      The Dagliç is a breed of sheep that is found i...          33  
4      Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                  ...         ...  
27995  The coherent transport of magnetic information...         286  
27996  We present a study of the infrared properties ...         330  
27997  This paper presents the results of a study of ...         339  
27998  Two tripartite schemes are put forward with sh...          98  
27999  In quantum computing, sharing single-qubit ope...          95  

[28000 rows x 4 columns]

### Datasets Gabungan Full

In [ ]:
train_fullMerg_df = pd.concat([train_wiki_df, train_abstract_df]).reset_index(drop=True)
val_fullMerg_df = pd.concat([val_wiki_df, val_abstract_df]).reset_index(drop=True)
test_fullMerg_df = pd.concat([test_wiki_df, test_abstract_df]).reset_index(drop=True)

In [ ]:
print(f"Ukuran Train abstract-Label: {train_fullMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_fullMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_fullMerg_df.shape}")

Ukuran Train abstract-Label: (158000, 4)
Ukuran Test abstract-Label: (19000, 4)
Ukuran Val abstract-Label: (19000, 4)


In [ ]:
train_fullMerg_df

title  label  \
0                                            James Scobie      0   
1                                            James Scobie      1   
2                                            Dagliç sheep      0   
3                                            Dagliç sheep      1   
4                                           Hamdard India      0   
...                                                   ...    ...   
157995  Effects of bonding type and interface geometry...      1   
157996  GOODS-Herschel: The far-infrared view of star ...      0   
157997  GOODS-Herschel: The far-infrared view of star ...      1   
157998  Single-qubit peration sharing with Bell and W ...      0   
157999  Single-qubit peration sharing with Bell and W ...      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
157995  The coherent transport of magnetic information...         286  
157996  We present a study of the infrared properties ...         330  
157997  This paper presents the results of a study of ...         339  
157998  Two tripartite schemes are put forward with sh...          98  
157999  In quantum computing, sharing single-qubit ope...          95  

[158000 rows x 4 columns]

# Initialize Function

In [ ]:
import tensorflow as tf
import numpy as np
from transformers import AutoTokenizer, TFT5EncoderModel, TFAutoModelForSequenceClassification
from sklearn.metrics import precision_score, recall_score, f1_score

## Preprocessing

In [ ]:
def preprocess_text(dataframe, tokenizer, max_length=256):
    tokenizer.padding_side = 'left'

    inputs = tokenizer(
        dataframe['text'].tolist(),
        padding='max_length',
        truncation=True,
        return_tensors="tf",
        max_length=max_length
    )

    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return {"input_ids": input_ids, "attention_mask": attention_mask}

In [ ]:
def preprocess_label(dataframe):
    train_labels = dataframe['label']
    # Convert labels to float32
    train_labels = train_labels.astype('float32')

    return train_labels

## Build Model

In [ ]:
def load_model(base_name, tokenizerBase=AutoTokenizer, modelBase=TFAutoModelForSequenceClassification):
    tokenizer = tokenizerBase.from_pretrained(base_name)
    model = modelBase.from_pretrained(base_name)

    # Freeze model layers
    for layer in model.layers:
        layer.trainable = False

    return tokenizer, model

In [ ]:
def create_model(model, isT5=False):
    # Define model inputs
    input_ids = tf.keras.Input(shape=(256,), dtype=tf.int32, name='input_ids')
    attention_mask = tf.keras.Input(shape=(256,), dtype=tf.int32, name='attention_mask')

    if isT5:
        # Pass inputs through the T5 encoder
        encoder_outputs = model({'input_ids': input_ids, 'attention_mask': attention_mask})
        sequence_output = encoder_outputs.last_hidden_state

        # Pool the sequence output
        output = tf.keras.layers.GlobalAveragePooling1D()(sequence_output)

    else:
        # Pass inputs through model
        model_output = model({'input_ids': input_ids, 'attention_mask': attention_mask})

        # Get logits output
        output = model_output.logits

    # Add classification layer
    classifier = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(output)

    # Create and compile the model
    final_model = tf.keras.Model(inputs={'input_ids': input_ids, 'attention_mask': attention_mask}, outputs=classifier)
    final_model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return final_model

## Training Function

In [ ]:
def train_model(model, tokenizer, train_data, val_data, epochs=5, batch_size=128):
    # Preprocess training and validation data
    train_abstract_inputs = preprocess_text(train_data, tokenizer)
    val_abstract_inputs = preprocess_text(val_data, tokenizer)

    train_labels = preprocess_label(train_data)
    val_labels = preprocess_label(val_data)

    print(train_abstract_inputs)
    print("\n-------------START TRAINING-------------\n")

    history = model.fit(
                    train_abstract_inputs, train_labels,
                    validation_data=(val_abstract_inputs, val_labels),
                    epochs=epochs,
                    batch_size=batch_size
                )

    return history

In [ ]:
def evaluate_f1score(data_test, tokenizer, model, path, treshold=0.5):
    test_inputs = preprocess_text(data_test, tokenizer)
    y_test = data_test['label']

    y_pred_prob = model.predict(test_inputs)
    y_pred = (y_pred_prob > treshold).astype(int)

    # Calculate precision, recall, and F1 score
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print('Precision:', precision)
    print('Recall:', recall)
    print('F1 Score:', f1)

    # Define the file path where you want to save the results
    file_path = path

    # Open the file in write mode and write the results
    with open(file_path, 'w') as file:
        file.write(f"Precision: {precision}\n")
        file.write(f"Recall: {recall}\n")
        file.write(f"F1 Score: {f1_score}\n")

    print(f"Results saved to {file_path}")

In [ ]:
def save_history(history_data, path):
    # Extract history data
    history_dict = history_data.history

    # Create a DataFrame from the history dictionary
    history_df = pd.DataFrame(history_dict)
    print(history_df)

    # Save the DataFrame to a CSV file
    history_df.to_csv(path, index=False)

In [ ]:
def save_model(model, path):
    model.save(path, save_format='tf')

# Training Model

## XLNET Model Training

### 1. XLNet-Abstract

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_abstract_hist = train_model(xlnet_model, xlnet_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  659,   499,   806, ...,   240,     4,     3],
       [   67,    52,   757, ...,  1059,     4,     3],
       [ 2834,  6490, 17666, ...,   351,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 572s 5s/step - loss: 0.8339 - accuracy: 0.3556 - val_loss: 0.7757 - val_accuracy: 0.3883
Epoch 2/5
110/110 [==============================] - 538s 5s/step - loss: 0.7844 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt")

188/188 [==============================] - 167s 851ms/step
Precision: 0.5422443107507193
Recall: 0.691
F1 Score: 0.6076505935805364
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt


In [ ]:
save_history(xlnet_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.833882  0.355643  0.775709      0.388333
1  0.784434  0.394429  0.736654      0.453000
2  0.743877  0.461500  0.703010      0.527000
3  0.710569  0.515786  0.675797      0.583667
4  0.684187  0.561429  0.653269      0.628000


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_abstract.h5")

### 2. XLNet-Wiki

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_wiki_hist = train_model(xlnet_model, xlnet_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [ 4319,   117, 11407, ...,  5808,     4,     3],
       [   32,    27,    24, ...,    60,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 4886s 4s/step - loss: 0.6815 - accuracy: 0.5643 - val_loss: 0.6583 - val_accuracy: 0.6029
Epoch 2/5
1125/1125 [==============================] - 4850s 4s/step - loss: 0.6555 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_wiki.txt")

188/188 [==============================] - 160s 815ms/step
Precision: 0.6204180551348076
Recall: 0.6826666666666666
F1 Score: 0.6500555467386129
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_wiki.txt


In [ ]:
save_history(xlnet_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_wiki_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.681533  0.564326  0.658333      0.602938
1  0.655474  0.614549  0.644936      0.638875
2  0.646506  0.629625  0.635650      0.649250
3  0.639427  0.640493  0.628526      0.658813
4  0.635299  0.646299  0.622394      0.669813


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_wiki.h5")

### 3. XLNet-Balance-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification_1 (TFXLNetForSe  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 quenceClassification)       gits=(None, 6),                                                

In [ ]:
xlnet_balMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 1060s 5s/step - loss: 0.9823 - accuracy: 0.4986 - val_loss: 0.7900 - val_accuracy: 0.4978
Epoch 2/5
219/219 [==============================] - 1034s 5s/step - loss: 0.7522 - accuracy: 

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_balMerg.txt")

188/188 [==============================] - 159s 810ms/step
Precision: 0.5659041394335512
Recall: 0.6926666666666667
F1 Score: 0.6229016786570744
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_balMerg.txt


In [ ]:
save_history(xlnet_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.982350  0.498643  0.789985      0.497833
1  0.752209  0.496250  0.706602      0.503000
2  0.712801  0.514500  0.691013      0.566333
3  0.696158  0.544179  0.680460      0.590167
4  0.684148  0.566750  0.672608      0.599833


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_balMerg.h5")

### 4. XLNet-Full-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_fullMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 5712s 5s/step - loss: 0.7006 - accuracy: 0.5574 - val_loss: 0.6636 - val_accuracy: 0.6055
Epoch 2/5
1235/1235 [==============================] - 5672s 5s/step - loss: 0.6598 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_fullMerg.txt")

188/188 [==============================] - 167s 851ms/step
Precision: 0.6208489748772741
Recall: 0.7166666666666667
F1 Score: 0.6653257001392542
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_fullMerg.txt


In [ ]:
save_history(xlnet_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_fullMerg_history.csv")

In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_fullMerg.h5")

## ERNIE Model Training

### 1. ERNIE-Abstract

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                             

In [ ]:
ernie_abstract_hist = train_model(ernie_model, ernie_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[    1,  4850,  9749, ..., 11452,  1499,     2],
       [    1,  2089,  3730, ..., 11617, 10032,     2],
       [    1,  4675, 17963, ..., 17963,  1904,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    0,     0,     0, ...,  3777,    42,     2],
       [    0,     0,     0, ...,  9478,    42,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 353s 3s/step - loss: 1.5597 - accuracy: 0.5014 - val_loss: 1.4603 - val_accuracy: 0.5010
Epoch 2/5
110/110 [==============================] - 311s 3s/step - loss: 1.0611 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt")

188/188 [==============================] - 109s 531ms/step
Precision: 0.522300036859565
Recall: 0.4723333333333333
F1 Score: 0.49606161386311914
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt


In [ ]:
save_history(ernie_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  1.559722  0.501429  1.460291      0.501000
1  1.061074  0.501500  0.993786      0.509000
2  0.819745  0.507714  0.799731      0.529333
3  0.752833  0.522286  0.742585      0.546000
4  0.738667  0.525071  0.723356      0.558000


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_abstract.h5")

### 2. ERNIE-Wiki

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification_1 (TFBertForSequ  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 enceClassification)         10),                                                           

In [ ]:
ernie_wiki_hist = train_model(ernie_model, ernie_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  5841,  9499, ..., 11898,  9570,     2],
       [    1,  1499,  2775, ...,  9701,  9742,     2],
       [    0,     0,     0, ..., 11272,    42,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 2774s 2s/step - loss: 0.7615 - accuracy: 0.5094 - val_loss: 0.6800 - val_accuracy: 0.5856
Epoch 2/5
1125/1125 [==============================] - 2750s 2s/step - loss: 0.6677 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_wiki.txt")

188/188 [==============================] - 104s 508ms/step
Precision: 0.5838365071992568
Recall: 0.419
F1 Score: 0.4878711430234814
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_wiki.txt


In [ ]:
save_history(ernie_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_wiki_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.761479  0.509410  0.679959      0.585625
1  0.667726  0.596917  0.650398      0.624750
2  0.656533  0.612153  0.639566      0.637000
3  0.653245  0.616035  0.637917      0.638750
4  0.652846  0.615687  0.636357      0.639687


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_wiki.h5")

### 3. ERNIE-Balance-Merge

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification_1 (TFBertForSequ  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 enceClassification)         10),                                                           

In [ ]:
ernie_balMerg_hist = train_model(ernie_model, ernie_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    0,     0,     0, ...,  3777,    42,     2],
       [    0,     0,     0, ...,  9478,    42,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 654s 3s/step - loss: 1.2821 - accuracy: 0.4901 - val_loss: 1.0260 - val_accuracy: 0.4780
Epoch 2/5
219/219 [==============================] - 621s 3s/step - loss: 0.8229 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_balMerg.txt")

188/188 [==============================] - 109s 531ms/step
Precision: 0.5322151224707136
Recall: 0.6663333333333333
F1 Score: 0.5917702782711664
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_balMerg.txt


In [ ]:
save_history(ernie_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  1.282145  0.490143  1.026009      0.478000
1  0.822874  0.500250  0.822095      0.501167
2  0.747790  0.528214  0.763462      0.516667
3  0.721039  0.535929  0.731217      0.524000
4  0.705499  0.549250  0.711788      0.534333


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_balMerg.h5")

### 4. ERNIE-Full-Merge

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                             

In [ ]:
ernie_fullMerg_hist = train_model(ernie_model, ernie_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    0,     0,     0, ...,  3777,    42,     2],
       [    0,     0,     0, ...,  9478,    42,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 3126s 3s/step - loss: 0.7619 - accuracy: 0.5576 - val_loss: 0.6651 - val_accuracy: 0.5975
Epoch 2/5
1235/1235 [==============================] - 3086s 2s/step - loss: 0.6693 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_fullMerg.txt")

188/188 [==============================] - 105s 510ms/step
Precision: 0.5865058424425179
Recall: 0.5186666666666667
F1 Score: 0.5505041570847338
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_fullMerg.txt


In [ ]:
save_history(ernie_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_fullMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.761884  0.557595  0.665119      0.597474
1  0.669305  0.592247  0.655946      0.610947
2  0.668380  0.592544  0.655959      0.607789
3  0.666532  0.594804  0.654109      0.614105
4  0.665569  0.597430  0.653764      0.615842


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_fullMerg.h5")

## T5 Model Training

### 1. T5-Abstract

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tft5_encoder_model_2 (TFT5  TFBaseModelOutput(last_hid   1096285   ['attention_mask[0][0]',      
 EncoderModel)               den_state=(None, 256, 768)   44         'input_ids[0][0]']           
                             , hidden_states=None, atte                                     

In [ ]:
t5_abstract_hist = train_model(t5_model, t5_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  638,   413,   697, ...,   125, 15439,     1],
       [   86,    48,   810, ...,     6,    62,     1],
       [ 1563,  1514,     2, ...,     2,    18,     1],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [    0,     0,     0, ...,    80,     5,     1],
       [    0,     0,     0, ...,  5275,     5,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 321s 3s/step - loss: 0.5835 - accuracy: 0.7699 - val_loss: 0.4846 - val_accuracy: 0.8463
Epoch 2/5
110/110 [==============================] - 288s 3s/step - loss: 0.4344 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt")

188/188 [==============================] - 100s 482ms/step
Precision: 0.7419614147909968
Recall: 0.923
F1 Score: 0.8226381461675579
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt


In [ ]:
save_history(t5_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.583533  0.769929  0.484587      0.846333
1  0.434370  0.890714  0.394272      0.854000
2  0.358287  0.908143  0.333935      0.877667
3  0.309184  0.920500  0.294674      0.899667
4  0.275022  0.929357  0.274339      0.899000


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_abstract.h5")

### 2. T5-Wiki

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['attention_mask[0][0]',      
 coderModel)                 den_state=(None, 256, 768)   44         'input_ids[0][0]']           
                             , hidden_states=None, atte                                       

In [ ]:
t5_wiki_hist = train_model(t5_model, t5_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[    0,     0,     0, ...,  3654,     5,     1],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [    0,     0,     0, ...,   477,     5,     1],
       ...,
       [  961,    63,  4612, ...,    86,  5541,     1],
       [   37,    19,     3, ...,    10,  3411,     1],
       [    0,     0,     0, ..., 20325,     5,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 2662s 2s/step - loss: 0.3053 - accuracy: 0.8754 - val_loss: 0.2257 - val_accuracy: 0.9250
Epoch 2/5
1125/1125 [==============================] - 2625s 2s/step - loss: 0.1687 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_wiki.txt")

188/188 [==============================] - 94s 454ms/step
Precision: 0.8490264921800191
Recall: 0.8866666666666667
F1 Score: 0.867438447741725
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_wiki.txt


In [ ]:
save_history(t5_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_wiki_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.305285  0.875444  0.225733      0.925000
1  0.168739  0.950090  0.177389      0.934125
2  0.127121  0.963931  0.174444      0.928187
3  0.105878  0.969382  0.169067      0.928062
4  0.093189  0.972049  0.155638      0.935000


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_wiki.h5")

### 3. T5-Balance-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tft5_encoder_model_1 (TFT5  TFBaseModelOutput(last_hid   1096285   ['attention_mask[0][0]',      
 EncoderModel)               den_state=(None, 256, 768)   44         'input_ids[0][0]']           
                             , hidden_states=None, atte                                     

In [ ]:
t5_balMerg_hist = train_model(t5_model, t5_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[    0,     0,     0, ...,  3654,     5,     1],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [    0,     0,     0, ...,   477,     5,     1],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [    0,     0,     0, ...,    80,     5,     1],
       [    0,     0,     0, ...,  5275,     5,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 608s 3s/step - loss: 0.5207 - accuracy: 0.7723 - val_loss: 0.4289 - val_accuracy: 0.8333
Epoch 2/5
219/219 [==============================] - 575s 3s/step - loss: 0.3782 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_balMerg.txt")

188/188 [==============================] - 99s 480ms/step
Precision: 0.8430804863925883
Recall: 0.9706666666666667
F1 Score: 0.9023861171366595
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_balMerg.txt


In [ ]:
save_history(t5_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.520731  0.772321  0.428923      0.833333
1  0.378170  0.868750  0.350767      0.865167
2  0.311461  0.900036  0.303842      0.884000
3  0.270647  0.914750  0.277154      0.892333
4  0.241680  0.924786  0.261545      0.898000


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_balMerg.h5")

### 4. T5-Full-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['attention_mask[0][0]',      
 coderModel)                 den_state=(None, 256, 768)   44         'input_ids[0][0]']           
                             , hidden_states=None, atte                                     

In [ ]:
t5_fullMerg_hist = train_model(t5_model, t5_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[    0,     0,     0, ...,  3654,     5,     1],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [    0,     0,     0, ...,   477,     5,     1],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [    0,     0,     0, ...,    80,     5,     1],
       [    0,     0,     0, ...,  5275,     5,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 3050s 2s/step - loss: 0.3243 - accuracy: 0.8693 - val_loss: 0.2497 - val_accuracy: 0.9145
Epoch 2/5
1235/1235 [==============================] - 3015s 2s/step - loss: 0.1800 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_fullMerg.txt")

188/188 [==============================] - 99s 481ms/step
Precision: 0.8473998294970162
Recall: 0.994
F1 Score: 0.9148642429820525
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_fullMerg.txt


In [ ]:
save_history(t5_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_fullMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.324349  0.869323  0.249727      0.914526
1  0.179996  0.946051  0.216128      0.914158
2  0.137300  0.959297  0.193172      0.921421
3  0.116688  0.963968  0.189727      0.921368
4  0.104366  0.967513  0.187026      0.921316


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_fullMerg.h5")