# Install Library

In [1]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.5 MB/s eta 0:00:00


In [2]:
!pip install transformers

In [3]:
!pip install tensorflow

In [4]:
!pip install tf-keras

In [5]:
!pip install matplotlib

In [6]:
!pip install ipywidgets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.5 MB/s eta 0:00:00


In [7]:
!pip install sentencepiece

In [8]:
!pip install scikit-learn

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Load Datasets

## Load Data dari Hugging Face

In [10]:
from datasets import load_dataset
import pandas as pd

In [11]:
from huggingface_hub import login
login()

## Datasets Tunggal

### Wiki-Label Datasets

In [12]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
wiki_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "wiki_labeled")

wiki_dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/210000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/45000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/45000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 210000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
})

In [13]:
# Konversi dataset ke DataFrame Pandas
train_wiki_df = wiki_dataset["train"].to_pandas().iloc[:144000]
test_wiki_df = wiki_dataset["test"].to_pandas().iloc[:16000]
val_wiki_df = wiki_dataset["validation"].to_pandas().iloc[:16000]

In [14]:
print(f"Ukuran Train Wiki-Label: {train_wiki_df.shape}")
print(f"Ukuran Test Wiki-Label: {test_wiki_df.shape}")
print(f"Ukuran Val Wiki-Label: {val_wiki_df.shape}")

Ukuran Train Wiki-Label: (144000, 4)
Ukuran Test Wiki-Label: (16000, 4)
Ukuran Val Wiki-Label: (16000, 4)


In [15]:
train_wiki_df

title  label  \
0                   James Scobie      0   
1                   James Scobie      1   
2                   Dagliç sheep      0   
3                   Dagliç sheep      1   
4                  Hamdard India      0   
...                          ...    ...   
143995             Diggers' Song      1   
143996  Geylang International FC      0   
143997  Geylang International FC      1   
143998        Takayama Main Line      0   
143999        Takayama Main Line      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
143995  The "Diggers' Song" (also known as "Levellers'...         218  
143996  Geylang International Football Club is a profe...         166  
143997  Geylang International Football Club is a profe...         207  
143998  The  is a Japanese railway line between Gifu S...         180  
143999  The  is a Japanese railway line connecting the...          72  

[144000 rows x 4 columns]

### Research-Abstract-Label Datasets

In [16]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
abstract_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "research_abstracts_labeled")

abstract_dataset

Generating train split:   0%|          | 0/14000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 14000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
})

In [17]:
# Konversi dataset ke DataFrame Pandas
train_abstract_df = abstract_dataset["train"].to_pandas()
test_abstract_df = abstract_dataset["test"].to_pandas()
val_abstract_df = abstract_dataset["validation"].to_pandas()

In [18]:
print(f"Ukuran Train abstract-Label: {train_abstract_df.shape}")
print(f"Ukuran Test abstract-Label: {test_abstract_df.shape}")
print(f"Ukuran Val abstract-Label: {val_abstract_df.shape}")

Ukuran Train abstract-Label: (14000, 4)
Ukuran Test abstract-Label: (3000, 4)
Ukuran Val abstract-Label: (3000, 4)


In [19]:
train_abstract_df

title  label  \
0      Study of coupling loss on bi-columnar BSCCO/Ag...      0   
1      Study of coupling loss on bi-columnar BSCCO/Ag...      1   
2      Weighted Solyanik estimates for the strong max...      0   
3      Weighted Solyanik estimates for the strong max...      1   
4      SOFIA-EXES Observations of Betelgeuse during t...      0   
...                                                  ...    ...   
13995  Effects of bonding type and interface geometry...      1   
13996  GOODS-Herschel: The far-infrared view of star ...      0   
13997  GOODS-Herschel: The far-infrared view of star ...      1   
13998  Single-qubit peration sharing with Bell and W ...      0   
13999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      Coupling losses were studied in composite tape...         280  
1      In this study, we investigate the coupling los...         215  
2      Let $\mathsf M_{\mathsf S}$ denote the strong ...         332  
3      In this paper, we investigate Weighted Solyani...         225  
4      In 2019 October Betelgeuse began a decline in ...         268  
...                                                  ...         ...  
13995  The coherent transport of magnetic information...         286  
13996  We present a study of the infrared properties ...         330  
13997  This paper presents the results of a study of ...         339  
13998  Two tripartite schemes are put forward with sh...          98  
13999  In quantum computing, sharing single-qubit ope...          95  

[14000 rows x 4 columns]

## Datasets Gabungan

### Datasets Gabungan Balance

In [20]:
train_balMerg_df = pd.concat([train_wiki_df.iloc[:14000], train_abstract_df]).reset_index(drop=True)
val_balMerg_df = pd.concat([val_wiki_df.iloc[:3000], val_abstract_df]).reset_index(drop=True)
test_balMerg_df = pd.concat([test_wiki_df.iloc[:3000], test_abstract_df]).reset_index(drop=True)

In [21]:
print(f"Ukuran Train abstract-Label: {train_balMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_balMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_balMerg_df.shape}")

Ukuran Train abstract-Label: (28000, 4)
Ukuran Test abstract-Label: (6000, 4)
Ukuran Val abstract-Label: (6000, 4)


In [22]:
train_balMerg_df

title  label  \
0                                           James Scobie      0   
1                                           James Scobie      1   
2                                           Dagliç sheep      0   
3                                           Dagliç sheep      1   
4                                          Hamdard India      0   
...                                                  ...    ...   
27995  Effects of bonding type and interface geometry...      1   
27996  GOODS-Herschel: The far-infrared view of star ...      0   
27997  GOODS-Herschel: The far-infrared view of star ...      1   
27998  Single-qubit peration sharing with Bell and W ...      0   
27999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      James Scobie (29 November 1826 – 7 October 185...         175  
1      James Scobie (29 November 1826 – 7 October 189...         242  
2      The Dagliç is a breed of sheep found primarily...         152  
3      The Dagliç is a breed of sheep that is found i...          33  
4      Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                  ...         ...  
27995  The coherent transport of magnetic information...         286  
27996  We present a study of the infrared properties ...         330  
27997  This paper presents the results of a study of ...         339  
27998  Two tripartite schemes are put forward with sh...          98  
27999  In quantum computing, sharing single-qubit ope...          95  

[28000 rows x 4 columns]

### Datasets Gabungan Full

In [23]:
train_fullMerg_df = pd.concat([train_wiki_df, train_abstract_df]).reset_index(drop=True)
val_fullMerg_df = pd.concat([val_wiki_df, val_abstract_df]).reset_index(drop=True)
test_fullMerg_df = pd.concat([test_wiki_df, test_abstract_df]).reset_index(drop=True)

In [24]:
print(f"Ukuran Train abstract-Label: {train_fullMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_fullMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_fullMerg_df.shape}")

Ukuran Train abstract-Label: (158000, 4)
Ukuran Test abstract-Label: (19000, 4)
Ukuran Val abstract-Label: (19000, 4)


In [25]:
train_fullMerg_df

title  label  \
0                                            James Scobie      0   
1                                            James Scobie      1   
2                                            Dagliç sheep      0   
3                                            Dagliç sheep      1   
4                                           Hamdard India      0   
...                                                   ...    ...   
157995  Effects of bonding type and interface geometry...      1   
157996  GOODS-Herschel: The far-infrared view of star ...      0   
157997  GOODS-Herschel: The far-infrared view of star ...      1   
157998  Single-qubit peration sharing with Bell and W ...      0   
157999  Single-qubit peration sharing with Bell and W ...      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
157995  The coherent transport of magnetic information...         286  
157996  We present a study of the infrared properties ...         330  
157997  This paper presents the results of a study of ...         339  
157998  Two tripartite schemes are put forward with sh...          98  
157999  In quantum computing, sharing single-qubit ope...          95  

[158000 rows x 4 columns]

# Initialize Function

In [26]:
import tensorflow as tf
import numpy as np
from transformers import AutoTokenizer, TFT5EncoderModel, TFAutoModelForSequenceClassification
from sklearn.metrics import precision_score, recall_score, f1_score

## Preprocessing

In [27]:
def preprocess_text(dataframe, tokenizer, max_length=256):
    inputs = tokenizer(dataframe['text'].tolist(), padding=True, truncation=True, return_tensors="tf", max_length=max_length)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return {"input_ids": input_ids, "attention_mask": attention_mask}

In [28]:
def preprocess_label(dataframe):
    train_labels = dataframe['label']
    # Convert labels to float32
    train_labels = train_labels.astype('float32')

    return train_labels

## Build Model

In [29]:
def load_model(base_name, tokenizerBase=AutoTokenizer, modelBase=TFAutoModelForSequenceClassification):
    tokenizer = tokenizerBase.from_pretrained(base_name)
    model = modelBase.from_pretrained(base_name)

    # Freeze model layers
    for layer in model.layers:
        layer.trainable = False

    return tokenizer, model

In [30]:
def create_model(model, isT5=False):
    # Define model inputs
    input_ids = tf.keras.Input(shape=(256,), dtype=tf.int32, name='input_ids')
    attention_mask = tf.keras.Input(shape=(256,), dtype=tf.int32, name='attention_mask')

    if isT5:
        # Pass inputs through the T5 encoder
        encoder_outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = encoder_outputs.last_hidden_state

        # Pool the sequence output
        output = tf.keras.layers.GlobalAveragePooling1D()(sequence_output)

    else:
        # Pass inputs through model
        model_output = model({'input_ids': input_ids, 'attention_mask': attention_mask})

        # Get logits output
        output = model_output.logits

    # Add classification layer
    classifier = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(output)

    # Create and compile the model
    final_model = tf.keras.Model(inputs=[input_ids, attention_mask], outputs=classifier)
    final_model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
        )

    return final_model

## Training Function

In [31]:
def train_model(model, tokenizer, train_data, val_data, epochs=5, batch_size=128):
    # Preprocess training and validation data
    train_abstract_inputs = preprocess_text(train_data, tokenizer)
    val_abstract_inputs = preprocess_text(val_data, tokenizer)

    train_labels = preprocess_label(train_data)
    val_labels = preprocess_label(val_data)

    print(train_abstract_inputs)
    print("\n-------------START TRAINING-------------\n")

    history = model.fit(
                    train_abstract_inputs, train_labels,
                    validation_data=(val_abstract_inputs, val_labels),
                    epochs=epochs,
                    batch_size=batch_size
                )

    return history

In [32]:
def evaluate_f1score(data_test, tokenizer, model, path, treshold=0.5):
    test_inputs = preprocess_text(data_test, tokenizer)
    y_test = data_test['label']

    y_pred_prob = model.predict(test_inputs)
    y_pred = (y_pred_prob > treshold).astype(int)

    # Calculate precision, recall, and F1 score
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print('Precision:', precision)
    print('Recall:', recall)
    print('F1 Score:', f1)

    # Define the file path where you want to save the results
    file_path = path

    # Open the file in write mode and write the results
    with open(file_path, 'w') as file:
        file.write(f"Precision: {precision}\n")
        file.write(f"Recall: {recall}\n")
        file.write(f"F1 Score: {f1_score}\n")

    print(f"Results saved to {file_path}")

In [33]:
def save_history(history_data, path):
    # Extract history data
    history_dict = history_data.history

    # Create a DataFrame from the history dictionary
    history_df = pd.DataFrame(history_dict)
    print(history_df)

    # Save the DataFrame to a CSV file
    history_df.to_csv(path, index=False)

In [34]:
def save_model(model, path):
    model.save(path)

# Training Model

## XLNET Model Training

### 1. XLNet-Abstract

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/1.97k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/346 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/469M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_abstract_hist = train_model(xlnet_model, xlnet_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  659,   499,   806, ...,   240,     4,     3],
       [   67,    52,   757, ...,  1059,     4,     3],
       [ 2834,  6490, 17666, ...,   351,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 576s 5s/step - loss: 0.7492 - accuracy: 0.5283 - val_loss: 0.6850 - val_accuracy: 0.5427
Epoch 2/5
110/110 [==============================] - 603s 5s/step - loss: 0.6242 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt")

188/188 [==============================] - 165s 875ms/step
Precision: 0.6429374297489696
Recall: 0.572
F1 Score: 0.6053977773857823
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt


In [ ]:
save_history(xlnet_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.749216  0.528286  0.685015      0.542667
1  0.624156  0.619071  0.601839      0.648667
2  0.581600  0.700357  0.575427      0.712000
3  0.566495  0.723143  0.566126      0.732667
4  0.561245  0.730643  0.560304      0.737000


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. XLNet-Wiki

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/1.97k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/346 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/469M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_wiki_hist = train_model(xlnet_model, xlnet_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [ 4319,   117, 11407, ...,  5808,     4,     3],
       [   32,    27,    24, ...,    60,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 4902s 4s/step - loss: 0.7314 - accuracy: 0.5099 - val_loss: 0.6710 - val_accuracy: 0.6128
Epoch 2/5
1125/1125 [==============================] - 4871s 4s/step - loss: 0.6625 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_wiki.txt")

188/188 [==============================] - 161s 821ms/step
Precision: 0.6063037249283668
Recall: 0.7053333333333334
F1 Score: 0.6520801232665641
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_wiki.txt


In [ ]:
save_history(xlnet_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_wiki_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.731353  0.509917  0.671041      0.612813
1  0.662521  0.608111  0.647003      0.641187
2  0.650146  0.627271  0.638103      0.650625
3  0.643124  0.636285  0.630675      0.660625
4  0.637395  0.644917  0.624468      0.664000


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_wiki.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 3. XLNet-Balance-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_balMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 1117s 5s/step - loss: 0.7168 - accuracy: 0.4795 - val_loss: 0.6950 - val_accuracy: 0.5335
Epoch 2/5
219/219 [==============================] - 1068s 5s/step - loss: 0.6874 - accuracy: 

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_balMerg.txt")

188/188 [==============================] - 153s 776ms/step
Precision: 0.5849846497348591
Recall: 0.6986666666666667
F1 Score: 0.636791736290445
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_balMerg.txt


In [ ]:
save_history(xlnet_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.716794  0.479464  0.694958      0.533500
1  0.687388  0.557286  0.675605      0.559000
2  0.670499  0.594214  0.664607      0.591500
3  0.661689  0.609786  0.657979      0.606167
4  0.655108  0.621429  0.653881      0.611833


In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_balMerg.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 4. XLNet-Full-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification_1 (TFXLNetForSe  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 quenceClassification)       gits=(None, 6),                                                

In [ ]:
xlnet_fullMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[    5,     5,     5, ...,     9,     4,     3],
       [ 1173, 11256, 10698, ...,   237,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 5471s 4s/step - loss: 0.7297 - accuracy: 0.5483 - val_loss: 0.6728 - val_accuracy: 0.5809
Epoch 2/5
1235/1235 [==============================] - 5447s 4s/step - loss: 0.6615 - accu

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_fullMerg.txt")

188/188 [==============================] - 160s 820ms/step
Precision: 0.6228554812445478
Recall: 0.714
F1 Score: 0.6653207019723559
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_fullMerg.txt


In [ ]:
save_history(xlnet_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_fullMerg_history.csv")

In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_fullMerg.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


## ERNIE Model Training

### 1. ERNIE-Abstract

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/944 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/91.1k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/400M [00:00<?, ?B/s]

Some layers from the model checkpoint at seamew/THUCNews_ernie were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at seamew/THUCNews_ernie.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                           

In [ ]:
ernie_abstract_hist = train_model(ernie_model, ernie_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[    1,  4850,  9749, ..., 11452,  1499,     2],
       [    1,  2089,  3730, ..., 11617, 10032,     2],
       [    1,  4675, 17963, ..., 17963,  1904,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    1,  5724, 11446, ...,     0,     0,     0],
       [    1,  2089,  8942, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 357s 3s/step - loss: 0.7385 - accuracy: 0.5808 - val_loss: 0.7514 - val_accuracy: 0.5867
Epoch 2/5
110/110 [==============================] - 345s 3s/step - loss: 0.7123 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt")

188/188 [==============================] - 111s 540ms/step
Precision: 0.5826446280991735
Recall: 0.517
F1 Score: 0.5478629459554928
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt


In [ ]:
save_history(ernie_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.738519  0.580786  0.751408      0.586667
1  0.712301  0.582500  0.727170      0.588667
2  0.698068  0.579500  0.702468      0.590333
3  0.685196  0.584857  0.685912      0.596333
4  0.677283  0.590857  0.675631      0.599667


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. ERNIE-Wiki

In [49]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

Some layers from the model checkpoint at seamew/THUCNews_ernie were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at seamew/THUCNews_ernie.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [50]:
ernie_model = create_model(ernie_model)

In [51]:
ernie_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification_1 (TFBertForSequ  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 enceClassification)         10),                                                           

In [52]:
ernie_wiki_hist = train_model(ernie_model, ernie_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  5841,  9499, ..., 11898,  9570,     2],
       [    1,  1499,  2775, ...,  9701,  9742,     2],
       [    1,  1499,  2775, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 3041s 3s/step - loss: 0.6946 - accuracy: 0.5917 - val_loss: 0.6592 - val_accuracy: 0.6006
Epoch 2/5
1125/1125 [==============================] - 3015s 3s/step - loss: 0.6430 - accu

In [53]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_wiki.txt")

188/188 [==============================] - 112s 553ms/step
Precision: 0.5854251012145749
Recall: 0.723
F1 Score: 0.646979865771812
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_wiki.txt


In [ ]:
save_history(ernie_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_wiki_history.csv")

In [55]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_wiki.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 3. ERNIE-Balance-Merge

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/944 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/91.1k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/400M [00:00<?, ?B/s]

Some layers from the model checkpoint at seamew/THUCNews_ernie were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at seamew/THUCNews_ernie.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                           

In [ ]:
ernie_balMerg_hist = train_model(ernie_model, ernie_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    1,  5724, 11446, ...,     0,     0,     0],
       [    1,  2089,  8942, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 663s 3s/step - loss: 0.8402 - accuracy: 0.4767 - val_loss: 0.7663 - val_accuracy: 0.5283
Epoch 2/5
219/219 [==============================] - 590s 3s/step - loss: 0.7554 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_balMerg.txt")

188/188 [==============================] - 112s 486ms/step
Precision: 0.5764904386951631
Recall: 0.6833333333333333
F1 Score: 0.6253813300793166
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_balMerg.txt


In [ ]:
save_history(ernie_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.840243  0.476714  0.766283      0.528333
1  0.755415  0.514964  0.725298      0.546000
2  0.715062  0.535143  0.698904      0.562000
3  0.693401  0.552929  0.681783      0.574000
4  0.681355  0.567643  0.674592      0.581667


In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_balMerg.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 4. ERNIE-Full-Merge

In [42]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/944 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/91.1k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/400M [00:00<?, ?B/s]

Some layers from the model checkpoint at seamew/THUCNews_ernie were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at seamew/THUCNews_ernie.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [43]:
ernie_model = create_model(ernie_model)

In [44]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                           

In [45]:
ernie_fullMerg_hist = train_model(ernie_model, ernie_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[    1,  5219,  7004, ...,  9561,  6070,     2],
       [    1,  5219,  7004, ...,  6474, 10131,     2],
       [    1,  1499,  7102, ...,  9751,  4640,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    1,  5724, 11446, ...,     0,     0,     0],
       [    1,  2089,  8942, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 3398s 3s/step - loss: 0.6939 - accuracy: 0.5788 - val_loss: 0.6531 - val_accuracy: 0.6077
Epoch 2/5
1235/1235 [==============================] - 3365s 3s/step - loss: 0.6469 - accu

In [46]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_fullMerg.txt")

188/188 [==============================] - 113s 555ms/step
Precision: 0.5779137975006375
Recall: 0.7553333333333333
F1 Score: 0.6548186678225689
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_fullMerg.txt


In [47]:
save_history(ernie_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_fullMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.693915  0.578829  0.653085      0.607684
1  0.646909  0.618589  0.654179      0.607316
2  0.644221  0.622373  0.655511      0.603526
3  0.642876  0.622690  0.645718      0.623526
4  0.641893  0.624146  0.647674      0.619579


In [48]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_fullMerg.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


## T5 Model Training

### 1. T5-Abstract

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

tokenizer_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.11.layer.2.DenseReluDense.wo.weight', 'decoder.block.3.layer.1.EncDecAttention.v.weight', 'decoder.block.8.layer.0.SelfAttention.o.weight', 'decoder.block.6.layer.1.layer_norm.weight', 'decoder.block.3.layer.2.DenseReluDense.wo.weight', 'decoder.block.5.layer.0.SelfAttention.q.weight', 'decoder.block.6.layer.1.EncDecAttention.o.weight', 'decoder.block.5.layer.2.layer_norm.weight', 'decoder.block.1.layer.1.EncDecAttention.q.weight', 'decoder.block.11.layer.0.layer_norm.weight', 'decoder.block.4.layer.0.SelfAttention.v.weight', 'decoder.block.4.layer.1.EncDecAttention.o.weight', 'decoder.block.5.layer.0.layer_norm.weight', 'decoder.block.7.layer.2.layer_norm.weight', 'decoder.block.10.layer.1.EncDecAttention.v.weight', 'decoder.block.0.layer.0.SelfAttention.v.weight', 'decoder.block.6.layer.0.SelfAttention.o.weight', 'decoder.block.10.layer.2.DenseReluDense.wo.weight', 'de

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 coderModel)                 den_state=(None, 256, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                     

In [ ]:
t5_abstract_hist = train_model(t5_model, t5_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  638,   413,   697, ...,   125, 15439,     1],
       [   86,    48,   810, ...,     6,    62,     1],
       [ 1563,  1514,     2, ...,     2,    18,     1],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [ 2759,  1469,  1408, ...,     0,     0,     0],
       [   86, 21353, 10937, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 373s 3s/step - loss: 0.5705 - accuracy: 0.8095 - val_loss: 0.4692 - val_accuracy: 0.8603
Epoch 2/5
110/110 [==============================] - 331s 3s/step - loss: 0.4212 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt")

188/188 [==============================] - 102s 488ms/step
Precision: 0.7426125379729357
Recall: 0.8963333333333333
F1 Score: 0.8122640084579368
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt


In [ ]:
save_history(t5_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.570527  0.809500  0.469199      0.860333
1  0.421234  0.896071  0.372463      0.880667
2  0.345463  0.914786  0.317664      0.896000
3  0.298089  0.925429  0.279291      0.912000
4  0.264363  0.935071  0.257406      0.914333


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. T5-Wiki

In [35]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

tokenizer_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.5.layer.1.EncDecAttention.k.weight', 'decoder.block.6.layer.1.layer_norm.weight', 'decoder.block.0.layer.2.layer_norm.weight', 'decoder.block.2.layer.0.SelfAttention.v.weight', 'decoder.block.6.layer.0.layer_norm.weight', 'decoder.block.8.layer.2.layer_norm.weight', 'decoder.block.9.layer.1.EncDecAttention.q.weight', 'decoder.block.1.layer.2.DenseReluDense.wo.weight', 'decoder.block.9.layer.0.layer_norm.weight', 'decoder.block.6.layer.1.EncDecAttention.v.weight', 'decoder.block.5.layer.0.layer_norm.weight', 'decoder.block.11.layer.2.DenseReluDense.wi.weight', 'decoder.block.10.layer.0.layer_norm.weight', 'decoder.block.7.layer.2.DenseReluDense.wi.weight', 'decoder.block.2.layer.2.DenseReluDense.wo.weight', 'decoder.block.5.layer.0.SelfAttention.q.weight', 'decoder.block.6.layer.1.EncDecAttention.q.weight', 'decoder.block.9.layer.1.EncDecAttention.k.weight', 'decoder.bloc

In [36]:
t5_model = create_model(t5_model, isT5=True)

In [37]:
t5_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 coderModel)                 den_state=(None, 256, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                       

In [38]:
t5_wiki_hist = train_model(t5_model, t5_tokenizer, train_wiki_df, val_wiki_df)

{'input_ids': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[ 2549, 10711,  4232, ...,     0,     0,     0],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [   37,   878,  4707, ...,     0,     0,     0],
       ...,
       [  961,    63,  4612, ...,    86,  5541,     1],
       [   37,    19,     3, ...,    10,  3411,     1],
       [   37,    19,     3, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(144000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1125/1125 [==============================] - 2938s 3s/step - loss: 0.3030 - accuracy: 0.8768 - val_loss: 0.2172 - val_accuracy: 0.9296
Epoch 2/5
1125/1125 [==============================] - 2908s 3s/step - loss: 0.1682 - accu

In [39]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_wiki.txt")

188/188 [==============================] - 102s 496ms/step
Precision: 0.8594855305466238
Recall: 0.891
F1 Score: 0.8749590834697218
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_wiki.txt


In [40]:
save_history(t5_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_wiki_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.303030  0.876792  0.217184      0.929563
1  0.168230  0.949840  0.175277      0.937000
2  0.127940  0.962062  0.171084      0.931875
3  0.107781  0.967201  0.162321      0.933125
4  0.095271  0.970563  0.160614      0.932187


In [41]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_wiki.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 3. T5-Balance-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

tokenizer_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.0.layer.1.EncDecAttention.v.weight', 'decoder.block.5.layer.1.EncDecAttention.o.weight', 'decoder.block.3.layer.2.layer_norm.weight', 'decoder.block.7.layer.2.layer_norm.weight', 'decoder.block.7.layer.0.SelfAttention.k.weight', 'decoder.block.4.layer.1.EncDecAttention.v.weight', 'decoder.block.8.layer.2.layer_norm.weight', 'decoder.block.5.layer.1.EncDecAttention.q.weight', 'decoder.block.7.layer.2.DenseReluDense.wi.weight', 'decoder.block.0.layer.1.EncDecAttention.q.weight', 'decoder.block.3.layer.0.SelfAttention.k.weight', 'decoder.block.10.layer.2.layer_norm.weight', 'decoder.block.0.layer.2.DenseReluDense.wi.weight', 'decoder.block.10.layer.0.SelfAttention.q.weight', 'decoder.block.6.layer.0.SelfAttention.v.weight', 'decoder.block.5.layer.2.DenseReluDense.wo.weight', 'decoder.block.2.layer.1.EncDecAttention.o.weight', 'decoder.block.11.layer.2.DenseReluDense.wi.weig

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 coderModel)                 den_state=(None, 256, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                       

In [ ]:
t5_balMerg_hist = train_model(t5_model, t5_tokenizer, train_balMerg_df, val_balMerg_df)

{'input_ids': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[ 2549, 10711,  4232, ...,     0,     0,     0],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [   37,   878,  4707, ...,     0,     0,     0],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [ 2759,  1469,  1408, ...,     0,     0,     0],
       [   86, 21353, 10937, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(28000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
219/219 [==============================] - 649s 3s/step - loss: 0.5345 - accuracy: 0.7519 - val_loss: 0.4338 - val_accuracy: 0.8373
Epoch 2/5
219/219 [==============================] - 605s 3s/step - loss: 0.3827 - accuracy: 0.

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_balMerg.txt")

188/188 [==============================] - 94s 455ms/step
Precision: 0.8564692012967875
Recall: 0.9686666666666667
F1 Score: 0.9091193492882841
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_balMerg.txt


In [ ]:
save_history(t5_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_balMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.534479  0.751893  0.433838      0.837333
1  0.382717  0.872714  0.345471      0.877500
2  0.312540  0.901929  0.298235      0.893500
3  0.269340  0.917571  0.262234      0.909500
4  0.240224  0.926786  0.252471      0.905500


In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_balMerg.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 4. T5-Full-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

tokenizer_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.0.layer.1.EncDecAttention.k.weight', 'decoder.block.8.layer.0.SelfAttention.v.weight', 'decoder.block.9.layer.2.DenseReluDense.wo.weight', 'decoder.block.3.layer.1.EncDecAttention.o.weight', 'decoder.block.2.layer.2.layer_norm.weight', 'decoder.block.5.layer.0.SelfAttention.v.weight', 'decoder.block.4.layer.1.EncDecAttention.q.weight', 'decoder.block.9.layer.0.SelfAttention.k.weight', 'decoder.block.8.layer.1.EncDecAttention.q.weight', 'decoder.block.4.layer.2.layer_norm.weight', 'decoder.block.2.layer.0.SelfAttention.q.weight', 'decoder.block.1.layer.0.SelfAttention.k.weight', 'decoder.block.7.layer.0.SelfAttention.o.weight', 'decoder.block.4.layer.0.SelfAttention.q.weight', 'decoder.block.1.layer.0.SelfAttention.v.weight', 'decoder.block.11.layer.2.layer_norm.weight', 'decoder.final_layer_norm.weight', 'decoder.block.3.layer.1.EncDecAttention.k.weight', 'decoder.block.

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 coderModel)                 den_state=(None, 256, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                     

In [52]:
t5_fullMerg_hist = train_model(t5_model, t5_tokenizer, train_fullMerg_df, val_fullMerg_df)

{'input_ids': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[ 2549, 10711,  4232, ...,     0,     0,     0],
       [ 2549, 10711,  4232, ...,    16,   960,     1],
       [   37,   878,  4707, ...,     0,     0,     0],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [ 2759,  1469,  1408, ...,     0,     0,     0],
       [   86, 21353, 10937, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(158000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
1235/1235 [==============================] - 2927s 2s/step - loss: 0.3214 - accuracy: 0.8748 - val_loss: 0.2462 - val_accuracy: 0.9159
Epoch 2/5
1235/1235 [==============================] - 2901s 2s/step - loss: 0.1784 - accu

In [53]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_fullMerg.txt")

188/188 [==============================] - 93s 454ms/step
Precision: 0.8545977011494252
Recall: 0.9913333333333333
F1 Score: 0.9179012345679012
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_fullMerg.txt


In [54]:
save_history(t5_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_fullMerg_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.321363  0.874816  0.246182      0.915947
1  0.178411  0.946842  0.194825      0.927421
2  0.137470  0.958411  0.193065      0.919263
3  0.117433  0.963975  0.184585      0.923053
4  0.104971  0.966994  0.186461      0.921000


In [55]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_fullMerg_history.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
