# Install Library

In [2]:
!pip install datasets

In [3]:
!pip install transformers

In [4]:
!pip install tensorflow

In [5]:
!pip install tf-keras

In [6]:
!pip install matplotlib

In [7]:
!pip install ipywidgets

In [8]:
!pip install sentencepiece

In [9]:
!pip install scikit-learn

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Load Datasets

## Load Data dari Hugging Face

In [11]:
from datasets import load_dataset
import pandas as pd

In [12]:
from huggingface_hub import login
login()

## Datasets Tunggal

### Wiki-Label Datasets

In [13]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
wiki_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "wiki_labeled")

wiki_dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 210000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
})

In [14]:
# Konversi dataset ke DataFrame Pandas
train_wiki_df = wiki_dataset["train"].to_pandas()
test_wiki_df = wiki_dataset["test"].to_pandas()
val_wiki_df = wiki_dataset["validation"].to_pandas()

In [15]:
print(f"Ukuran Train Wiki-Label: {train_wiki_df.shape}")
print(f"Ukuran Test Wiki-Label: {test_wiki_df.shape}")
print(f"Ukuran Val Wiki-Label: {val_wiki_df.shape}")

Ukuran Train Wiki-Label: (210000, 4)
Ukuran Test Wiki-Label: (45000, 4)
Ukuran Val Wiki-Label: (45000, 4)


In [16]:
train_wiki_df

title  label  \
0                     James Scobie      0   
1                     James Scobie      1   
2                     Dagliç sheep      0   
3                     Dagliç sheep      1   
4                    Hamdard India      0   
...                            ...    ...   
209995  Esperanza mía (soundtrack)      1   
209996    Macquarie Street, Hobart      0   
209997    Macquarie Street, Hobart      1   
209998              Daniel L. Ryan      0   
209999              Daniel L. Ryan      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
209995  Esperanza mía is the official soundtrack of th...         136  
209996  Macquarie Street a major one way street passin...         175  
209997  Macquarie Street a major one way street in Hob...         113  
209998  Daniel Leo Ryan (September 28, 1930 – December...         189  
209999  Daniel Leo Ryan (September 28, 1930 – February...         146  

[210000 rows x 4 columns]

### Research-Abstract-Label Datasets

In [17]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
abstract_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "research_abstracts_labeled")

abstract_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 14000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
})

In [18]:
# Konversi dataset ke DataFrame Pandas
train_abstract_df = abstract_dataset["train"].to_pandas()
test_abstract_df = abstract_dataset["test"].to_pandas()
val_abstract_df = abstract_dataset["validation"].to_pandas()

In [19]:
print(f"Ukuran Train abstract-Label: {train_abstract_df.shape}")
print(f"Ukuran Test abstract-Label: {test_abstract_df.shape}")
print(f"Ukuran Val abstract-Label: {val_abstract_df.shape}")

Ukuran Train abstract-Label: (14000, 4)
Ukuran Test abstract-Label: (3000, 4)
Ukuran Val abstract-Label: (3000, 4)


In [20]:
train_abstract_df

title  label  \
0      Study of coupling loss on bi-columnar BSCCO/Ag...      0   
1      Study of coupling loss on bi-columnar BSCCO/Ag...      1   
2      Weighted Solyanik estimates for the strong max...      0   
3      Weighted Solyanik estimates for the strong max...      1   
4      SOFIA-EXES Observations of Betelgeuse during t...      0   
...                                                  ...    ...   
13995  Effects of bonding type and interface geometry...      1   
13996  GOODS-Herschel: The far-infrared view of star ...      0   
13997  GOODS-Herschel: The far-infrared view of star ...      1   
13998  Single-qubit peration sharing with Bell and W ...      0   
13999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      Coupling losses were studied in composite tape...         280  
1      In this study, we investigate the coupling los...         215  
2      Let $\mathsf M_{\mathsf S}$ denote the strong ...         332  
3      In this paper, we investigate Weighted Solyani...         225  
4      In 2019 October Betelgeuse began a decline in ...         268  
...                                                  ...         ...  
13995  The coherent transport of magnetic information...         286  
13996  We present a study of the infrared properties ...         330  
13997  This paper presents the results of a study of ...         339  
13998  Two tripartite schemes are put forward with sh...          98  
13999  In quantum computing, sharing single-qubit ope...          95  

[14000 rows x 4 columns]

## Datasets Gabungan

### Datasets Gabungan Balance

In [21]:
train_balMerg_df = pd.concat([train_wiki_df.iloc[:14000], train_abstract_df]).reset_index(drop=True)
val_balMerg_df = pd.concat([val_wiki_df.iloc[:3000], val_abstract_df]).reset_index(drop=True)
test_balMerg_df = pd.concat([test_wiki_df.iloc[:3000], test_abstract_df]).reset_index(drop=True)

In [22]:
print(f"Ukuran Train abstract-Label: {train_balMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_balMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_balMerg_df.shape}")

Ukuran Train abstract-Label: (28000, 4)
Ukuran Test abstract-Label: (6000, 4)
Ukuran Val abstract-Label: (6000, 4)


In [23]:
train_balMerg_df

title  label  \
0                                           James Scobie      0   
1                                           James Scobie      1   
2                                           Dagliç sheep      0   
3                                           Dagliç sheep      1   
4                                          Hamdard India      0   
...                                                  ...    ...   
27995  Effects of bonding type and interface geometry...      1   
27996  GOODS-Herschel: The far-infrared view of star ...      0   
27997  GOODS-Herschel: The far-infrared view of star ...      1   
27998  Single-qubit peration sharing with Bell and W ...      0   
27999  Single-qubit peration sharing with Bell and W ...      1   

                                                    text  word_count  
0      James Scobie (29 November 1826 – 7 October 185...         175  
1      James Scobie (29 November 1826 – 7 October 189...         242  
2      The Dagliç is a breed of sheep found primarily...         152  
3      The Dagliç is a breed of sheep that is found i...          33  
4      Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                  ...         ...  
27995  The coherent transport of magnetic information...         286  
27996  We present a study of the infrared properties ...         330  
27997  This paper presents the results of a study of ...         339  
27998  Two tripartite schemes are put forward with sh...          98  
27999  In quantum computing, sharing single-qubit ope...          95  

[28000 rows x 4 columns]

### Datasets Gabungan Full

In [24]:
train_fullMerg_df = pd.concat([train_wiki_df, train_abstract_df]).reset_index(drop=True)
val_fullMerg_df = pd.concat([val_wiki_df, val_abstract_df]).reset_index(drop=True)
test_fullMerg_df = pd.concat([test_wiki_df, test_abstract_df]).reset_index(drop=True)

In [25]:
print(f"Ukuran Train abstract-Label: {train_fullMerg_df.shape}")
print(f"Ukuran Test abstract-Label: {val_fullMerg_df.shape}")
print(f"Ukuran Val abstract-Label: {test_fullMerg_df.shape}")

Ukuran Train abstract-Label: (224000, 4)
Ukuran Test abstract-Label: (48000, 4)
Ukuran Val abstract-Label: (48000, 4)


In [26]:
train_fullMerg_df

title  label  \
0                                            James Scobie      0   
1                                            James Scobie      1   
2                                            Dagliç sheep      0   
3                                            Dagliç sheep      1   
4                                           Hamdard India      0   
...                                                   ...    ...   
223995  Effects of bonding type and interface geometry...      1   
223996  GOODS-Herschel: The far-infrared view of star ...      0   
223997  GOODS-Herschel: The far-infrared view of star ...      1   
223998  Single-qubit peration sharing with Bell and W ...      0   
223999  Single-qubit peration sharing with Bell and W ...      1   

                                                     text  word_count  
0       James Scobie (29 November 1826 – 7 October 185...         175  
1       James Scobie (29 November 1826 – 7 October 189...         242  
2       The Dagliç is a breed of sheep found primarily...         152  
3       The Dagliç is a breed of sheep that is found i...          33  
4       Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                   ...         ...  
223995  The coherent transport of magnetic information...         286  
223996  We present a study of the infrared properties ...         330  
223997  This paper presents the results of a study of ...         339  
223998  Two tripartite schemes are put forward with sh...          98  
223999  In quantum computing, sharing single-qubit ope...          95  

[224000 rows x 4 columns]

# Initialize Function

In [27]:
import tensorflow as tf
import numpy as np
from transformers import AutoTokenizer, TFT5EncoderModel, TFAutoModelForSequenceClassification
from sklearn.metrics import precision_score, recall_score, f1_score

## Preprocessing

In [28]:
def preprocess_text(dataframe, tokenizer, max_length=256):
    inputs = tokenizer(dataframe['text'].tolist(), padding=True, truncation=True, return_tensors="tf", max_length=max_length)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return {"input_ids": input_ids, "attention_mask": attention_mask}

In [29]:
def preprocess_label(dataframe):
    train_labels = dataframe['label']
    # Convert labels to float32
    train_labels = train_labels.astype('float32')

    return train_labels

## Build Model

In [30]:
def load_model(base_name, tokenizerBase=AutoTokenizer, modelBase=TFAutoModelForSequenceClassification):
    tokenizer = tokenizerBase.from_pretrained(base_name)
    model = modelBase.from_pretrained(base_name)

    # Freeze model layers
    for layer in model.layers:
        layer.trainable = False

    return tokenizer, model

In [31]:
def create_model(model, isT5=False):
    # Define model inputs
    input_ids = tf.keras.Input(shape=(256,), dtype=tf.int32, name='input_ids')
    attention_mask = tf.keras.Input(shape=(256,), dtype=tf.int32, name='attention_mask')

    if isT5:
        # Pass inputs through the T5 encoder
        encoder_outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = encoder_outputs.last_hidden_state

        # Pool the sequence output
        output = tf.keras.layers.GlobalAveragePooling1D()(sequence_output)

    else:
        # Pass inputs through model
        model_output = model({'input_ids': input_ids, 'attention_mask': attention_mask})

        # Get logits output
        output = model_output.logits

    # Add classification layer
    classifier = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(output)

    # Create and compile the model
    final_model = tf.keras.Model(inputs=[input_ids, attention_mask], outputs=classifier)
    final_model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
        )

    return final_model

## Training Function

In [32]:
def train_model(model, tokenizer, train_data, val_data, epochs=5, batch_size=128):
    # Preprocess training and validation data
    train_abstract_inputs = preprocess_text(train_data, tokenizer)
    val_abstract_inputs = preprocess_text(val_data, tokenizer)

    train_labels = preprocess_label(train_data)
    val_labels = preprocess_label(val_data)

    print(train_abstract_inputs)
    print("\n-------------START TRAINING-------------\n")

    history = model.fit(
                    train_abstract_inputs, train_labels,
                    validation_data=(val_abstract_inputs, val_labels),
                    epochs=epochs,
                    batch_size=batch_size
                )

    return history

In [33]:
def evaluate_f1score(data_test, tokenizer, model, path, treshold=0.5):
    test_inputs = preprocess_text(data_test, tokenizer)
    y_test = data_test['label']

    y_pred_prob = model.predict(test_inputs)
    y_pred = (y_pred_prob > treshold).astype(int)

    # Calculate precision, recall, and F1 score
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print('Precision:', precision)
    print('Recall:', recall)
    print('F1 Score:', f1)

    # Define the file path where you want to save the results
    file_path = path

    # Open the file in write mode and write the results
    with open(file_path, 'w') as file:
        file.write(f"Precision: {precision}\n")
        file.write(f"Recall: {recall}\n")
        file.write(f"F1 Score: {f1_score}\n")

    print(f"Results saved to {file_path}")

In [34]:
def save_history(history_data, path):
    # Extract history data
    history_dict = history_data.history

    # Create a DataFrame from the history dictionary
    history_df = pd.DataFrame(history_dict)
    print(history_df)

    # Save the DataFrame to a CSV file
    history_df.to_csv(path, index=False)

In [35]:
def save_model(model, path):
    model.save(path)

# Training Model

## XLNET Model Training

### 1. XLNet-Abstract

In [35]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/1.97k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/346 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/469M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [36]:
xlnet_model = create_model(xlnet_model)

In [37]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [38]:
xlnet_abstract_hist = train_model(xlnet_model, xlnet_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  659,   499,   806, ...,   240,     4,     3],
       [   67,    52,   757, ...,  1059,     4,     3],
       [ 2834,  6490, 17666, ...,   351,     4,     3],
       ...,
       [  122,  1200,  7579, ...,   131,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3],
       [    5,     5,     5, ...,     9,     4,     3]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 576s 5s/step - loss: 0.7492 - accuracy: 0.5283 - val_loss: 0.6850 - val_accuracy: 0.5427
Epoch 2/5
110/110 [==============================] - 603s 5s/step - loss: 0.6242 - accuracy: 0.

In [47]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt")

188/188 [==============================] - 165s 875ms/step
Precision: 0.6429374297489696
Recall: 0.572
F1 Score: 0.6053977773857823
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/xlnet_abstract.txt


In [43]:
save_history(xlnet_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.749216  0.528286  0.685015      0.542667
1  0.624156  0.619071  0.601839      0.648667
2  0.581600  0.700357  0.575427      0.712000
3  0.566495  0.723143  0.566126      0.732667
4  0.561245  0.730643  0.560304      0.737000


In [44]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. XLNet-Wiki

In [36]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFXLNetForSequenceClassification.

All the layers of TFXLNetForSequenceClassification were initialized from the model checkpoint at rubakha/xlnet-new.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetForSequenceClassification for predictions without further training.


In [37]:
xlnet_model = create_model(xlnet_model)

In [38]:
xlnet_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173135   ['attention_mask[0][0]',      
 sification (TFXLNetForSequ  cationOutput(loss=None, lo   42         'input_ids[0][0]']           
 enceClassification)         gits=(None, 6),                                                  

In [ ]:
xlnet_wiki_hist = train_model(xlnet_model, xlnet_tokenizer, train_wiki_df, val_wiki_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_wiki.txt")

In [ ]:
save_history(xlnet_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_wiki_history.csv")

In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_wiki.h5")

### 3. XLNet-Balance-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

In [ ]:
xlnet_balMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_balMerg_df, val_balMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_balMerg.txt")

In [ ]:
save_history(xlnet_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_balMerg_history.csv")

In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_balMerg.h5")

### 4. XLNet-Full-Merge

In [ ]:
base_name = 'rubakha/xlnet-new'
xlnet_tokenizer, xlnet_model = load_model(base_name)

In [ ]:
xlnet_model = create_model(xlnet_model)

In [ ]:
xlnet_model.summary()

In [ ]:
xlnet_fullMerg_hist = train_model(xlnet_model, xlnet_tokenizer, train_fullMerg_df, val_fullMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, xlnet_tokenizer, xlnet_model, "/content/drive/MyDrive/history-skripsi/f1score-history/xlnet_fullMerg.txt")

In [ ]:
save_history(xlnet_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/xlnet_fullMerg_history.csv")

In [ ]:
save_model(xlnet_model, "/content/drive/MyDrive/history-skripsi/saved-model/xlnet_fullMerg.h5")

## ERNIE Model Training

### 1. ERNIE-Abstract

In [48]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/944 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/91.1k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/400M [00:00<?, ?B/s]

Some layers from the model checkpoint at seamew/THUCNews_ernie were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at seamew/THUCNews_ernie.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [49]:
ernie_model = create_model(ernie_model)

In [50]:
ernie_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 tf_bert_for_sequence_class  TFSequenceClassifierOutput   9987380   ['attention_mask[0][0]',      
 ification (TFBertForSequen  (loss=None, logits=(None,    2          'input_ids[0][0]']           
 ceClassification)           10),                                                           

In [51]:
ernie_abstract_hist = train_model(ernie_model, ernie_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[    1,  4850,  9749, ..., 11452,  1499,     2],
       [    1,  2089,  3730, ..., 11617, 10032,     2],
       [    1,  4675, 17963, ..., 17963,  1904,     2],
       ...,
       [    1,  3730, 10649, ...,  1662,  8368,     2],
       [    1,  5724, 11446, ...,     0,     0,     0],
       [    1,  2089,  8942, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 357s 3s/step - loss: 0.7385 - accuracy: 0.5808 - val_loss: 0.7514 - val_accuracy: 0.5867
Epoch 2/5
110/110 [==============================] - 345s 3s/step - loss: 0.7123 - accuracy: 0.

In [52]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt")

188/188 [==============================] - 111s 540ms/step
Precision: 0.5826446280991735
Recall: 0.517
F1 Score: 0.5478629459554928
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/ernie_abstract.txt


In [54]:
save_history(ernie_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.738519  0.580786  0.751408      0.586667
1  0.712301  0.582500  0.727170      0.588667
2  0.698068  0.579500  0.702468      0.590333
3  0.685196  0.584857  0.685912      0.596333
4  0.677283  0.590857  0.675631      0.599667


In [55]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. ERNIE-Wiki

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

In [ ]:
ernie_wiki_hist = train_model(ernie_model, ernie_tokenizer, train_wiki_df, val_wiki_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_wiki.txt")

In [ ]:
save_history(ernie_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_wiki_history.csv")

In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_wiki.h5")

### 3. ERNIE-Balance-Merge

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

In [ ]:
ernie_balMerg_hist = train_model(ernie_model, ernie_tokenizer, train_balMerg_df, val_balMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_balMerg.txt")

In [ ]:
save_history(ernie_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_balMerg_history.csv")

In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_balMerg.h5")

### 4. ERNIE-Full-Merge

In [ ]:
base_name = 'seamew/THUCNews_ernie'
ernie_tokenizer, ernie_model = load_model(base_name)

In [ ]:
ernie_model = create_model(ernie_model)

In [ ]:
ernie_model.summary()

In [ ]:
ernie_fullMerg_hist = train_model(ernie_model, ernie_tokenizer, train_fullMerg_df, val_fullMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, ernie_tokenizer, ernie_model, "/content/drive/MyDrive/history-skripsi/f1score-history/ernie_fullMerg.txt")

In [ ]:
save_history(ernie_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/ernie_fullMerg_history.csv")

In [ ]:
save_model(ernie_model, "/content/drive/MyDrive/history-skripsi/saved-model/ernie_fullMerg.h5")

## T5 Model Training

### 1. T5-Abstract

In [56]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

tokenizer_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.11.layer.2.DenseReluDense.wo.weight', 'decoder.block.3.layer.1.EncDecAttention.v.weight', 'decoder.block.8.layer.0.SelfAttention.o.weight', 'decoder.block.6.layer.1.layer_norm.weight', 'decoder.block.3.layer.2.DenseReluDense.wo.weight', 'decoder.block.5.layer.0.SelfAttention.q.weight', 'decoder.block.6.layer.1.EncDecAttention.o.weight', 'decoder.block.5.layer.2.layer_norm.weight', 'decoder.block.1.layer.1.EncDecAttention.q.weight', 'decoder.block.11.layer.0.layer_norm.weight', 'decoder.block.4.layer.0.SelfAttention.v.weight', 'decoder.block.4.layer.1.EncDecAttention.o.weight', 'decoder.block.5.layer.0.layer_norm.weight', 'decoder.block.7.layer.2.layer_norm.weight', 'decoder.block.10.layer.1.EncDecAttention.v.weight', 'decoder.block.0.layer.0.SelfAttention.v.weight', 'decoder.block.6.layer.0.SelfAttention.o.weight', 'decoder.block.10.layer.2.DenseReluDense.wo.weight', 'de

In [57]:
t5_model = create_model(t5_model, isT5=True)

In [58]:
t5_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 256)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 256)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model (TFT5En  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 coderModel)                 den_state=(None, 256, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                     

In [59]:
t5_abstract_hist = train_model(t5_model, t5_tokenizer, train_abstract_df, val_abstract_df)

{'input_ids': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[  638,   413,   697, ...,   125, 15439,     1],
       [   86,    48,   810, ...,     6,    62,     1],
       [ 1563,  1514,     2, ...,     2,    18,     1],
       ...,
       [  100,  1040,  6621, ...,     3,  4894,     1],
       [ 2759,  1469,  1408, ...,     0,     0,     0],
       [   86, 21353, 10937, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14000, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

-------------START TRAINING-------------

Epoch 1/5
110/110 [==============================] - 373s 3s/step - loss: 0.5705 - accuracy: 0.8095 - val_loss: 0.4692 - val_accuracy: 0.8603
Epoch 2/5
110/110 [==============================] - 331s 3s/step - loss: 0.4212 - accuracy: 0.

In [60]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt")

188/188 [==============================] - 102s 488ms/step
Precision: 0.7426125379729357
Recall: 0.8963333333333333
F1 Score: 0.8122640084579368
Results saved to /content/drive/MyDrive/history-skripsi/f1score-history/t5_abstract.txt


In [61]:
save_history(t5_abstract_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_abstract_history.csv")

       loss  accuracy  val_loss  val_accuracy
0  0.570527  0.809500  0.469199      0.860333
1  0.421234  0.896071  0.372463      0.880667
2  0.345463  0.914786  0.317664      0.896000
3  0.298089  0.925429  0.279291      0.912000
4  0.264363  0.935071  0.257406      0.914333


In [62]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_abstract.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### 2. T5-Wiki

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

In [ ]:
t5_wiki_hist = train_model(t5_model, t5_tokenizer, train_wiki_df, val_wiki_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_wiki.txt")

In [ ]:
save_history(t5_wiki_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_wiki_history.csv")

In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_wiki.h5")

### 3. T5-Balance-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

In [ ]:
t5_balMerg_hist = train_model(t5_model, t5_tokenizer, train_balMerg_df, val_balMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_balMerg.txt")

In [ ]:
save_history(t5_balMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_balMerg_history.csv")

In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_balMerg.h5")

### 4. T5-Full-Merge

In [ ]:
base_name = 'michelecafagna26/t5-base-finetuned-sst2-sentiment'
t5_tokenizer, t5_model = load_model(base_name, modelBase=TFT5EncoderModel)

In [ ]:
t5_model = create_model(t5_model, isT5=True)

In [ ]:
t5_model.summary()

In [ ]:
t5_fullMerg_hist = train_model(t5_model, t5_tokenizer, train_fullMerg_df, val_fullMerg_df)

In [ ]:
test_data = test_balMerg_df
evaluate_f1score(test_data, t5_tokenizer, t5_model, "/content/drive/MyDrive/history-skripsi/f1score-history/t5_fullMerg.txt")

In [ ]:
save_history(t5_fullMerg_hist, "/content/drive/MyDrive/history-skripsi/train-history/t5_fullMerg_history.csv")

In [ ]:
save_model(t5_model, "/content/drive/MyDrive/history-skripsi/saved-model/t5_fullMerg_history.h5")