# Install Library

In [1]:
# %pip install datasets

In [2]:
# %pip install transformers

In [3]:
# %pip install sentencepiece

In [4]:
# %pip install ipywidgets

In [5]:
# %pip install ernie

In [6]:
# %pip install seaborn

# Load Data dan Model

## Load Data dari Hugging Face

In [7]:
from datasets import load_dataset
import pandas as pd

In [8]:
from huggingface_hub import login
login()

## Datasets Tunggal

### Wiki-Label Datasets

In [9]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
wiki_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "wiki_labeled")

wiki_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 210000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
})

In [10]:
# Konversi dataset ke DataFrame Pandas
train_wiki_df = wiki_dataset["train"].to_pandas().loc[:4999]
test_wiki_df = wiki_dataset["test"].to_pandas().loc[:999]
val_wiki_df = wiki_dataset["validation"].to_pandas().loc[:999]

In [11]:
print(f"Ukuran Train Wiki-Label: {train_wiki_df.shape}")
print(f"Ukuran Test Wiki-Label: {test_wiki_df.shape}")
print(f"Ukuran Val Wiki-Label: {val_wiki_df.shape}")

Ukuran Train Wiki-Label: (5000, 4)
Ukuran Test Wiki-Label: (1000, 4)
Ukuran Val Wiki-Label: (1000, 4)


In [12]:
train_wiki_df

title  label  \
0            James Scobie      0   
1            James Scobie      1   
2            Dagliç sheep      0   
3            Dagliç sheep      1   
4           Hamdard India      0   
...                   ...    ...   
4995           Cecil Weir      1   
4996  Health care quality      0   
4997  Health care quality      1   
4998   Sumatran frogmouth      0   
4999   Sumatran frogmouth      1   

                                                   text  word_count  
0     James Scobie (29 November 1826 – 7 October 185...         175  
1     James Scobie (29 November 1826 – 7 October 189...         242  
2     The Dagliç is a breed of sheep found primarily...         152  
3     The Dagliç is a breed of sheep that is found i...          33  
4     Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                 ...         ...  
4995  Cecil James Mullo Weir (4 December 1897 – 21 S...         196  
4996  Health care quality is a level of value provid...         290  
4997  Health care quality is a level of quality of c...         205  
4998  The Sumatran frogmouth (Batrachostomus poliolo...         173  
4999  The Sumatran frogmouth (Batrachostomus poliolo...          48  

[5000 rows x 4 columns]

### Research-Abstract-Label Datasets

In [13]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
abstract_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "research_abstracts_labeled")

abstract_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 14000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
})

In [14]:
# Konversi dataset ke DataFrame Pandas
train_abstract_df = abstract_dataset["train"].to_pandas().loc[:4999]
test_abstract_df = abstract_dataset["test"].to_pandas().loc[:999]
val_abstract_df = abstract_dataset["validation"].to_pandas().loc[:999]

In [15]:
print(f"Ukuran Train abstract-Label: {train_abstract_df.shape}")
print(f"Ukuran Test abstract-Label: {test_abstract_df.shape}")
print(f"Ukuran Val abstract-Label: {val_abstract_df.shape}")

Ukuran Train abstract-Label: (5000, 4)
Ukuran Test abstract-Label: (1000, 4)
Ukuran Val abstract-Label: (1000, 4)


In [16]:
train_abstract_df

title  label  \
0     Study of coupling loss on bi-columnar BSCCO/Ag...      0   
1     Study of coupling loss on bi-columnar BSCCO/Ag...      1   
2     Weighted Solyanik estimates for the strong max...      0   
3     Weighted Solyanik estimates for the strong max...      1   
4     SOFIA-EXES Observations of Betelgeuse during t...      0   
...                                                 ...    ...   
4995  Local Spectral Weight of a Luttinger Liquid: E...      1   
4996  Yukawa Corrections to gamma gamma --> b\bar{b}...      0   
4997  Yukawa Corrections to gamma gamma --> b\bar{b}...      1   
4998  Herschel-PACS Observations of Far-IR CO Line E...      0   
4999  Herschel-PACS Observations of Far-IR CO Line E...      1   

                                                   text  word_count  
0     Coupling losses were studied in composite tape...         280  
1     In this study, we investigate the coupling los...         215  
2     Let $\mathsf M_{\mathsf S}$ denote the strong ...         332  
3     In this paper, we investigate Weighted Solyani...         225  
4     In 2019 October Betelgeuse began a decline in ...         268  
...                                                 ...         ...  
4995  This research paper investigates the local spe...         104  
4996  We study the Yukawa corrections to the gamma g...         155  
4997  In this paper, we investigate the Yukawa corre...         143  
4998  We report the detection of far-IR CO rotationa...         334  
4999  This study presents new Herschel-PACS far-infr...         317  

[5000 rows x 4 columns]

## Datasets Gabungan

### Datasets Gabungan Full

In [17]:
train_group_all_df = pd.concat([train_wiki_df.iloc[:2500], train_abstract_df.iloc[:2500]]).reset_index(drop=True)
val_group_all_df = pd.concat([val_wiki_df.iloc[:500], val_abstract_df.iloc[:500]]).reset_index(drop=True)
test_group_all_df = pd.concat([test_wiki_df.iloc[:500], test_abstract_df.iloc[:500]]).reset_index(drop=True)

In [18]:
print(f"Ukuran Train abstract-Label: {train_group_all_df.shape}")
print(f"Ukuran Test abstract-Label: {val_group_all_df.shape}")
print(f"Ukuran Val abstract-Label: {test_group_all_df.shape}")

Ukuran Train abstract-Label: (5000, 4)
Ukuran Test abstract-Label: (1000, 4)
Ukuran Val abstract-Label: (1000, 4)


In [19]:
train_group_all_df

title  label  \
0                                          James Scobie      0   
1                                          James Scobie      1   
2                                          Dagliç sheep      0   
3                                          Dagliç sheep      1   
4                                         Hamdard India      0   
...                                                 ...    ...   
4995  Probing the dark-matter halos of cluster galax...      1   
4996  Einstein in 1916: "On the Quantum Theory of Ra...      0   
4997  Einstein in 1916: "On the Quantum Theory of Ra...      1   
4998  Finding Appropriate Traffic Regulations via Gr...      0   
4999  Finding Appropriate Traffic Regulations via Gr...      1   

                                                   text  word_count  
0     James Scobie (29 November 1826 – 7 October 185...         175  
1     James Scobie (29 November 1826 – 7 October 189...         242  
2     The Dagliç is a breed of sheep found primarily...         152  
3     The Dagliç is a breed of sheep that is found i...          33  
4     Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                 ...         ...  
4995  The existence of dark matter, which does not i...         274  
4996  In this contribution I discuss a peak in Einst...          51  
4997  "In 1916, Albert Einstein published a paper ti...          51  
4998  Appropriate traffic regulations, e.g. planned ...         206  
4999  The increasing complexity of modern transporta...         196  

[5000 rows x 4 columns]

# Test Sampel 10 Data

In [20]:
sampel_train = train_wiki_df.loc[0:9]
sampel_train

title  label  \
0             James Scobie      0   
1             James Scobie      1   
2             Dagliç sheep      0   
3             Dagliç sheep      1   
4            Hamdard India      0   
5            Hamdard India      1   
6  Berkeley Public Library      0   
7  Berkeley Public Library      1   
8                     Såne      0   
9                     Såne      1   

                                                text  word_count  
0  James Scobie (29 November 1826 – 7 October 185...         175  
1  James Scobie (29 November 1826 – 7 October 189...         242  
2  The Dagliç is a breed of sheep found primarily...         152  
3  The Dagliç is a breed of sheep that is found i...          33  
4  Hamdard Laboratories (India), is a Unani pharm...         160  
5  Hamdard Laboratories (India), is a Unani pharm...         125  
6  The Berkeley Public Library is the public libr...         164  
7  The Berkeley Public Library is the public libr...          92  
8  The Såne-sheep is a breed of Danish origin. In...         223  
9  The Såne-sheep is a breed of Danish sheep that...          71

In [21]:
sampel_test = test_wiki_df.loc[0:9]
sampel_test

title  label  \
0  Jum Jainudin Akbar      0   
1  Jum Jainudin Akbar      1   
2     Daphne Oxenford      0   
3     Daphne Oxenford      1   
4      MAX Light Rail      0   
5      MAX Light Rail      1   
6        Giulio Zardo      0   
7        Giulio Zardo      1   
8  Artashes Shahinian      0   
9  Artashes Shahinian      1   

                                                text  word_count  
0  Jum Jainudin Akbar (3 September 1963 – 11 Nove...         185  
1  Jum Jainudin Akbar (3 September 1963 – 18 Nove...         168  
2  Daphne Margaret du Grivel Oxenford (31 October...         181  
3  Daphne Margaret du Grivel Oxenford (31 October...         142  
4  MAX Light Rail (for Metropolitan Area Express)...         264  
5  MAX Light Rail (for Metropolitan Area Express)...         209  
6  Giulio Zardo (born July 14, 1980 in Montreal, ...         178  
7  Giulio Zardo (born July 14, 1980 in Milan) is ...          80  
8  Artashes Shahinyan (, December 19, 1906 – May ...         241  
9  Artashes Shahinyan (, December 19, 1906 – June...         219

In [22]:
sampel_val = val_wiki_df.loc[0:9]
sampel_val

title  label  \
0  Morgan (2012 film)      0   
1  Morgan (2012 film)      1   
2             Lachung      0   
3             Lachung      1   
4  Fountain (Duchamp)      0   
5  Fountain (Duchamp)      1   
6          Spiro Crne      0   
7          Spiro Crne      1   
8      Anthony Wilden      0   
9      Anthony Wilden      1   

                                                text  word_count  
0  Morgan is a 2012 gay film directed by Michael ...         154  
1  Morgan is a 2012 gay film directed by Tom McCa...          73  
2  Lachung is a town and hill station in northeas...         193  
3  Lachung is a town and hill station in the stat...          40  
4  Fountain is a readymade sculpture by Marcel Du...         247  
5  Fountain is a readymade sculpture by Marcel Du...         221  
6  Spiro Crne (; died 22 April 1881) was a rebel ...         341  
7  Spiro Crne (; died 22 April 1881) was a Serbia...         124  
8  Anthony George Wilden (14 December 1935 – 29 D...         166  
9  Anthony George Wilden (14 December 1935 – 21 O...         209

# Load Model

### ERNIE

In [56]:
import tensorflow as tf
import numpy as np
from transformers import AutoTokenizer, TFT5EncoderModel

In [57]:
tokenizer = AutoTokenizer.from_pretrained("michelecafagna26/t5-base-finetuned-sst2-sentiment")
t5_encoder = TFT5EncoderModel.from_pretrained('michelecafagna26/t5-base-finetuned-sst2-sentiment')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFT5EncoderModel: ['decoder.block.0.layer.1.EncDecAttention.q.weight', 'decoder.block.4.layer.0.SelfAttention.v.weight', 'decoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight', 'decoder.block.9.layer.0.SelfAttention.q.weight', 'decoder.block.9.layer.1.layer_norm.weight', 'decoder.block.0.layer.1.EncDecAttention.v.weight', 'decoder.block.10.layer.1.EncDecAttention.q.weight', 'decoder.block.11.layer.0.SelfAttention.v.weight', 'decoder.block.2.layer.0.SelfAttention.q.weight', 'decoder.block.4.layer.2.layer_norm.weight', 'decoder.block.0.layer.1.EncDecAttention.o.weight', 'decoder.block.9.layer.0.SelfAttention.v.weight', 'decoder.block.2.layer.0.SelfAttention.v.weight', 'decoder.block.1.layer.2.DenseReluDense.wo.weight', 'decoder.block.8.layer.0.layer_norm.weight', 'decoder.block.10.layer.0.layer_norm.weight', 'decoder.block.6.layer.2.layer_norm.weight', 'decoder.block.8.layer.2.layer_norm.we

In [58]:
t5_encoder.summary()

Model: "tft5_encoder_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 shared (Embedding)          multiple                  24674304  
                                                                 
 encoder (TFT5MainLayer)     multiple                  109628544 
                                                                 
Total params: 109628544 (418.20 MB)
Trainable params: 109628544 (418.20 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
# Freeze XLNet layers
for layer in t5_encoder.layers:
    layer.trainable = False

In [60]:
# Define model inputs
input_ids = tf.keras.Input(shape=(120,), dtype=tf.int32, name='input_ids')
attention_mask = tf.keras.Input(shape=(120,), dtype=tf.int32, name='attention_mask')

# Pass inputs through the T5 encoder
encoder_outputs = t5_encoder(input_ids=input_ids, attention_mask=attention_mask)
sequence_output = encoder_outputs.last_hidden_state

# Pool the sequence output and add a classification layer
pooled_output = tf.keras.layers.GlobalAveragePooling1D()(sequence_output)
classifier = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(pooled_output)

# Create the final model
t5_model = tf.keras.Model(inputs=[input_ids, attention_mask], outputs=classifier)

# Compile the model
t5_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [61]:
t5_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 120)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 120)]                0         []                            
 )                                                                                                
                                                                                                  
 tft5_encoder_model_1 (TFT5  TFBaseModelOutput(last_hid   1096285   ['input_ids[0][0]',           
 EncoderModel)               den_state=(None, 120, 768)   44         'attention_mask[0][0]']      
                             , hidden_states=None, atte                                     

In [62]:
def preprocess_text(text, tokenizer, max_length=120):
    inputs = tokenizer(text, padding=True, truncation=True, return_tensors="tf", max_length=max_length)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return input_ids, attention_mask

In [63]:
train_texts = train_abstract_df['text'].tolist()
val_texts = val_abstract_df['text'].tolist()

train_input_ids, train_attention_mask = preprocess_text(train_texts, tokenizer)
val_input_ids, val_attention_mask = preprocess_text(val_texts, tokenizer)

train_labels = np.array(train_abstract_df['label'].tolist())
val_labels = np.array(val_abstract_df['label'].tolist())

train_inputs = {
    "input_ids": train_input_ids,
    "attention_mask": train_attention_mask,
}

val_inputs = {
    "input_ids": val_input_ids,
    "attention_mask": val_attention_mask,
}

In [64]:
train_inputs

{'input_ids': <tf.Tensor: shape=(5000, 120), dtype=int32, numpy=
 array([[  638,   413,   697, ...,     7,    28,     1],
        [   86,    48,   810, ..., 16032,    57,     1],
        [ 1563,  1514,     2, ...,    89,   205,     1],
        ...,
        [   86,    48,  1040, ...,    57,     8,     1],
        [  101,   934,     8, ..., 22924,     6,     1],
        [  100,   810,  6621, ...,  7028,  1464,     1]])>,
 'attention_mask': <tf.Tensor: shape=(5000, 120), dtype=int32, numpy=
 array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]])>}

In [65]:
# Train the model
t5_model.fit(
    train_inputs, train_labels, 
    validation_data=(val_inputs, val_labels), 
    epochs=2, 
    batch_size=32
)

Epoch 1/2


157/157 [==============================] - 7854s 50s/step - loss: 0.5708 - accuracy: 0.7962 - val_loss: 0.4715 - val_accuracy: 0.8620
Epoch 2/2
157/157 [==============================] - 8053s 51s/step - loss: 0.4231 - accuracy: 0.8732 - val_loss: 0.3796 - val_accuracy: 0.8750
