# Install Library

In [1]:
# %pip install datasets

In [2]:
# %pip install transformers

In [3]:
# %pip install sentencepiece

In [4]:
# %pip install ipywidgets

In [5]:
# %pip install tensorflow

In [6]:
# %pip install matplotlib

In [7]:
# %pip install scikit-learn

In [8]:
# %pip install tf-keras

# Load Data dan Model

## Load Data dari Hugging Face

In [9]:
from datasets import load_dataset
import pandas as pd

In [10]:
from huggingface_hub import login
login()

## Datasets Tunggal

### Wiki-Label Datasets

In [11]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
wiki_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "wiki_labeled")

wiki_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 210000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 45000
    })
})

In [12]:
# Konversi dataset ke DataFrame Pandas
train_wiki_df = wiki_dataset["train"].to_pandas().loc[:4999]
test_wiki_df = wiki_dataset["test"].to_pandas().loc[:999]
val_wiki_df = wiki_dataset["validation"].to_pandas().loc[:999]

In [13]:
print(f"Ukuran Train Wiki-Label: {train_wiki_df.shape}")
print(f"Ukuran Test Wiki-Label: {test_wiki_df.shape}")
print(f"Ukuran Val Wiki-Label: {val_wiki_df.shape}")

Ukuran Train Wiki-Label: (5000, 4)
Ukuran Test Wiki-Label: (1000, 4)
Ukuran Val Wiki-Label: (1000, 4)


In [14]:
train_wiki_df

title  label  \
0            James Scobie      0   
1            James Scobie      1   
2            Dagliç sheep      0   
3            Dagliç sheep      1   
4           Hamdard India      0   
...                   ...    ...   
4995           Cecil Weir      1   
4996  Health care quality      0   
4997  Health care quality      1   
4998   Sumatran frogmouth      0   
4999   Sumatran frogmouth      1   

                                                   text  word_count  
0     James Scobie (29 November 1826 – 7 October 185...         175  
1     James Scobie (29 November 1826 – 7 October 189...         242  
2     The Dagliç is a breed of sheep found primarily...         152  
3     The Dagliç is a breed of sheep that is found i...          33  
4     Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                 ...         ...  
4995  Cecil James Mullo Weir (4 December 1897 – 21 S...         196  
4996  Health care quality is a level of value provid...         290  
4997  Health care quality is a level of quality of c...         205  
4998  The Sumatran frogmouth (Batrachostomus poliolo...         173  
4999  The Sumatran frogmouth (Batrachostomus poliolo...          48  

[5000 rows x 4 columns]

### Research-Abstract-Label Datasets

In [15]:
# If the dataset is gated/private, make sure you have run huggingface-cli login
abstract_dataset = load_dataset("NicolaiSivesind/human-vs-machine", "research_abstracts_labeled")

abstract_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 14000
    })
    test: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['title', 'label', 'text', 'word_count'],
        num_rows: 3000
    })
})

In [16]:
# Konversi dataset ke DataFrame Pandas
train_abstract_df = abstract_dataset["train"].to_pandas().loc[:4999]
test_abstract_df = abstract_dataset["test"].to_pandas().loc[:999]
val_abstract_df = abstract_dataset["validation"].to_pandas().loc[:999]

In [17]:
print(f"Ukuran Train abstract-Label: {train_abstract_df.shape}")
print(f"Ukuran Test abstract-Label: {test_abstract_df.shape}")
print(f"Ukuran Val abstract-Label: {val_abstract_df.shape}")

Ukuran Train abstract-Label: (5000, 4)
Ukuran Test abstract-Label: (1000, 4)
Ukuran Val abstract-Label: (1000, 4)


In [18]:
train_abstract_df

title  label  \
0     Study of coupling loss on bi-columnar BSCCO/Ag...      0   
1     Study of coupling loss on bi-columnar BSCCO/Ag...      1   
2     Weighted Solyanik estimates for the strong max...      0   
3     Weighted Solyanik estimates for the strong max...      1   
4     SOFIA-EXES Observations of Betelgeuse during t...      0   
...                                                 ...    ...   
4995  Local Spectral Weight of a Luttinger Liquid: E...      1   
4996  Yukawa Corrections to gamma gamma --> b\bar{b}...      0   
4997  Yukawa Corrections to gamma gamma --> b\bar{b}...      1   
4998  Herschel-PACS Observations of Far-IR CO Line E...      0   
4999  Herschel-PACS Observations of Far-IR CO Line E...      1   

                                                   text  word_count  
0     Coupling losses were studied in composite tape...         280  
1     In this study, we investigate the coupling los...         215  
2     Let $\mathsf M_{\mathsf S}$ denote the strong ...         332  
3     In this paper, we investigate Weighted Solyani...         225  
4     In 2019 October Betelgeuse began a decline in ...         268  
...                                                 ...         ...  
4995  This research paper investigates the local spe...         104  
4996  We study the Yukawa corrections to the gamma g...         155  
4997  In this paper, we investigate the Yukawa corre...         143  
4998  We report the detection of far-IR CO rotationa...         334  
4999  This study presents new Herschel-PACS far-infr...         317  

[5000 rows x 4 columns]

## Datasets Gabungan

### Datasets Gabungan Full

In [19]:
train_group_all_df = pd.concat([train_wiki_df.iloc[:2500], train_abstract_df.iloc[:2500]]).reset_index(drop=True)
val_group_all_df = pd.concat([val_wiki_df.iloc[:500], val_abstract_df.iloc[:500]]).reset_index(drop=True)
test_group_all_df = pd.concat([test_wiki_df.iloc[:500], test_abstract_df.iloc[:500]]).reset_index(drop=True)

In [20]:
print(f"Ukuran Train abstract-Label: {train_group_all_df.shape}")
print(f"Ukuran Test abstract-Label: {val_group_all_df.shape}")
print(f"Ukuran Val abstract-Label: {test_group_all_df.shape}")

Ukuran Train abstract-Label: (5000, 4)
Ukuran Test abstract-Label: (1000, 4)
Ukuran Val abstract-Label: (1000, 4)


In [21]:
train_group_all_df

title  label  \
0                                          James Scobie      0   
1                                          James Scobie      1   
2                                          Dagliç sheep      0   
3                                          Dagliç sheep      1   
4                                         Hamdard India      0   
...                                                 ...    ...   
4995  Probing the dark-matter halos of cluster galax...      1   
4996  Einstein in 1916: "On the Quantum Theory of Ra...      0   
4997  Einstein in 1916: "On the Quantum Theory of Ra...      1   
4998  Finding Appropriate Traffic Regulations via Gr...      0   
4999  Finding Appropriate Traffic Regulations via Gr...      1   

                                                   text  word_count  
0     James Scobie (29 November 1826 – 7 October 185...         175  
1     James Scobie (29 November 1826 – 7 October 189...         242  
2     The Dagliç is a breed of sheep found primarily...         152  
3     The Dagliç is a breed of sheep that is found i...          33  
4     Hamdard Laboratories (India), is a Unani pharm...         160  
...                                                 ...         ...  
4995  The existence of dark matter, which does not i...         274  
4996  In this contribution I discuss a peak in Einst...          51  
4997  "In 1916, Albert Einstein published a paper ti...          51  
4998  Appropriate traffic regulations, e.g. planned ...         206  
4999  The increasing complexity of modern transporta...         196  

[5000 rows x 4 columns]

# Test Sampel 10 Data

In [22]:
sampel_train = train_wiki_df.loc[0:9]
sampel_train

title  label  \
0             James Scobie      0   
1             James Scobie      1   
2             Dagliç sheep      0   
3             Dagliç sheep      1   
4            Hamdard India      0   
5            Hamdard India      1   
6  Berkeley Public Library      0   
7  Berkeley Public Library      1   
8                     Såne      0   
9                     Såne      1   

                                                text  word_count  
0  James Scobie (29 November 1826 – 7 October 185...         175  
1  James Scobie (29 November 1826 – 7 October 189...         242  
2  The Dagliç is a breed of sheep found primarily...         152  
3  The Dagliç is a breed of sheep that is found i...          33  
4  Hamdard Laboratories (India), is a Unani pharm...         160  
5  Hamdard Laboratories (India), is a Unani pharm...         125  
6  The Berkeley Public Library is the public libr...         164  
7  The Berkeley Public Library is the public libr...          92  
8  The Såne-sheep is a breed of Danish origin. In...         223  
9  The Såne-sheep is a breed of Danish sheep that...          71

In [23]:
sampel_test = test_wiki_df.loc[0:9]
sampel_test

title  label  \
0  Jum Jainudin Akbar      0   
1  Jum Jainudin Akbar      1   
2     Daphne Oxenford      0   
3     Daphne Oxenford      1   
4      MAX Light Rail      0   
5      MAX Light Rail      1   
6        Giulio Zardo      0   
7        Giulio Zardo      1   
8  Artashes Shahinian      0   
9  Artashes Shahinian      1   

                                                text  word_count  
0  Jum Jainudin Akbar (3 September 1963 – 11 Nove...         185  
1  Jum Jainudin Akbar (3 September 1963 – 18 Nove...         168  
2  Daphne Margaret du Grivel Oxenford (31 October...         181  
3  Daphne Margaret du Grivel Oxenford (31 October...         142  
4  MAX Light Rail (for Metropolitan Area Express)...         264  
5  MAX Light Rail (for Metropolitan Area Express)...         209  
6  Giulio Zardo (born July 14, 1980 in Montreal, ...         178  
7  Giulio Zardo (born July 14, 1980 in Milan) is ...          80  
8  Artashes Shahinyan (, December 19, 1906 – May ...         241  
9  Artashes Shahinyan (, December 19, 1906 – June...         219

In [24]:
sampel_val = val_wiki_df.loc[0:9]
sampel_val

title  label  \
0  Morgan (2012 film)      0   
1  Morgan (2012 film)      1   
2             Lachung      0   
3             Lachung      1   
4  Fountain (Duchamp)      0   
5  Fountain (Duchamp)      1   
6          Spiro Crne      0   
7          Spiro Crne      1   
8      Anthony Wilden      0   
9      Anthony Wilden      1   

                                                text  word_count  
0  Morgan is a 2012 gay film directed by Michael ...         154  
1  Morgan is a 2012 gay film directed by Tom McCa...          73  
2  Lachung is a town and hill station in northeas...         193  
3  Lachung is a town and hill station in the stat...          40  
4  Fountain is a readymade sculpture by Marcel Du...         247  
5  Fountain is a readymade sculpture by Marcel Du...         221  
6  Spiro Crne (; died 22 April 1881) was a rebel ...         341  
7  Spiro Crne (; died 22 April 1881) was a Serbia...         124  
8  Anthony George Wilden (14 December 1935 – 29 D...         166  
9  Anthony George Wilden (14 December 1935 – 21 O...         209

# Load Model

### XLNet

In [25]:
import tensorflow as tf
import numpy as np

from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve

In [26]:
import tensorflow as tf
from transformers import XLNetTokenizer, TFXLNetForSequenceClassification

In [43]:
# Load XLNet tokenizer
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')

# Load pre-trained XLNet model
xlnet_model = TFXLNetForSequenceClassification.from_pretrained('xlnet-base-cased')

d:\Mufti\Data\Unhas\Pembelajaran\Tugas Akhir (Skripsi)\Skripsi-Machine-vs-Human-Teks\.venv\lib\site-packages\tf_keras\src\initializers\initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
Some layers from the model checkpoint at xlnet-base-cased were not used when initializing TFXLNetForSequenceClassification: ['lm_loss']
- This IS expected if you are initializing TFXLNetForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLNetForSequenceClassification from the checkpoint of a model that you expect to be exactly id

In [44]:
xlnet_model.summary()

Model: "tfxl_net_for_sequence_classification_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 transformer (TFXLNetMainLa  multiple                  116718336 
 yer)                                                            
                                                                 
 sequence_summary (TFSequen  multiple                  590592    
 ceSummary)                                                      
                                                                 
 logits_proj (Dense)         multiple                  1538      
                                                                 
Total params: 117310466 (447.50 MB)
Trainable params: 117310466 (447.50 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [45]:
# Freeze XLNet layers
for layer in xlnet_model.layers:
    layer.trainable = False

In [73]:
# Add classification layer on top of XLNet
classifier = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')

# Define model inputs
input_ids = tf.keras.Input(shape=(120,), dtype=tf.int32, name='input_ids')
attention_mask = tf.keras.Input(shape=(120,), dtype=tf.int32, name='attention_mask')

# Pass inputs through XLNet model
xlnet_output = xlnet_model({'input_ids': input_ids, 'attention_mask': attention_mask})

# Get logits output
logits = xlnet_output.logits

# Pass logits through classifier
output = classifier(logits)

# Create and compile the model
model = tf.keras.Model(inputs=[input_ids, attention_mask], outputs=output)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



In [74]:
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 attention_mask (InputLayer  [(None, 120)]                0         []                            
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)      [(None, 120)]                0         []                            
                                                                                                  
 tfxl_net_for_sequence_clas  TFXLNetForSequenceClassifi   1173104   ['attention_mask[0][0]',      
 sification_1 (TFXLNetForSe  cationOutput(loss=None, lo   66         'input_ids[0][0]']           
 quenceClassification)       gits=(None, 2),                                                

In [75]:
# Tokenize and convert text data to input_ids and attention_mask
def preprocess_text(text):
    inputs = tokenizer(text, padding=True, truncation=True, return_tensors="tf", max_length=120)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return {"input_ids": input_ids, "attention_mask": attention_mask}

In [76]:
# Preprocess training and validation data
train_inputs = preprocess_text(train_abstract_df['text'].tolist())
val_inputs = preprocess_text(val_abstract_df['text'].tolist())

In [77]:
train_inputs

{'input_ids': <tf.Tensor: shape=(5000, 120), dtype=int32, numpy=
 array([[  659,   499,   806, ...,    30,     4,     3],
        [   67,    52,   757, ...,  4841,     4,     3],
        [ 2834,  6490, 17666, ...,   661,     4,     3],
        ...,
        [   67,    52,  1200, ...,    81,     4,     3],
        [  169,   419,    18, ..., 24470,     4,     3],
        [  122,   757,  7579, ...,  1729,     4,     3]])>,
 'attention_mask': <tf.Tensor: shape=(5000, 120), dtype=int32, numpy=
 array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]])>}

In [78]:
model.fit(train_inputs, train_abstract_df['label'], validation_data=(val_inputs, val_abstract_df['label']), epochs=2, batch_size=32)

Epoch 1/2
157/157 [==============================] - 6859s 43s/step - loss: 0.6932 - accuracy: 0.5144 - val_loss: 0.6904 - val_accuracy: 0.5400
Epoch 2/2
157/157 [==============================] - 6426s 41s/step - loss: 0.6917 - accuracy: 0.5260 - val_loss: 0.6903 - val_accuracy: 0.5400


In [79]:
test_inputs = preprocess_text(test_abstract_df['text'].tolist())

In [80]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(test_inputs, test_abstract_df['label'])

32/32 [==============================] - 970s 31s/step - loss: 0.6901 - accuracy: 0.5400


In [81]:
# Make predictions
predictions = model.predict(test_inputs)

32/32 [==============================] - 1059s 33s/step


In [82]:
predictions

array([[0.48236084],
       [0.4927978 ],
       [0.47500858],
       [0.4830067 ],
       [0.5217937 ],
       [0.46159014],
       [0.55005527],
       [0.5217053 ],
       [0.47117144],
       [0.47457445],
       [0.50257075],
       [0.50773233],
       [0.47774452],
       [0.486461  ],
       [0.4974346 ],
       [0.4942787 ],
       [0.4948299 ],
       [0.51484925],
       [0.4779362 ],
       [0.47848883],
       [0.51886016],
       [0.46447846],
       [0.48894858],
       [0.4896759 ],
       [0.5257397 ],
       [0.46460083],
       [0.47766107],
       [0.48740566],
       [0.49885067],
       [0.48402086],
       [0.5008652 ],
       [0.5036897 ],
       [0.48939934],
       [0.4846435 ],
       [0.5022034 ],
       [0.4566062 ],
       [0.4912652 ],
       [0.52492183],
       [0.49101672],
       [0.4743064 ],
       [0.52328193],
       [0.51102066],
       [0.5194057 ],
       [0.50858545],
       [0.47711343],
       [0.49604103],
       [0.48250717],
       [0.508

In [98]:
# Menghitung berapa banyak nilai probabilitas yang lebih besar dari 0.8
count_above_threshold = np.sum(predictions <= 0.5)

print("Jumlah nilai probabilitas di atas :", count_above_threshold)

Jumlah nilai probabilitas di atas : 618
